### ISSUE TITLE
Documentation: connection pooling

### ISSUE THREAD

**Issue by snowch** [cloudant/java-cloudant#100]
Please include documentation how to setup and configure connection pooling for this library.  For example:

 1. information on instantiating the library so that it can be shared, e.g. using a singleton
 1. calling out which methods are threadsafe and which aren't
 1. describe how to configure connection pooling
 1. describe how the library authenticates to Cloudant (using cookie or basic authentication)
 1. describe if session expiry gets handled automatically by the library [1].  if not, what does the library consumer need to do to handle this?
 1. how to use the library in JEE environments so that connection pooling can be configured at the app server level [2]

There is some information in this ticket: https://github.com/cloudant/java-cloudant/issues/34. However, it would be good if the [README.md](https://github.com/cloudant/java-cloudant/blob/master/README.md) covered the above info.

---
[1] this assumes the library uses cookie authentication.  The [docs](https://docs.cloudant.com/authentication.html#cookie-authentication) state that the cookie can be used until it expires.
[2] presumably this will require wrapping the library in a technology like [JCA](https://docs.oracle.com/javaee/5/tutorial/doc/bncjx.html) - [[more info]](https://www.jcp.org/en/jsr/detail?id=322)

**Comment by ricellis** [comment]
@snowch @mikerhodes do the changes from #102 address these questions adequately?

**Comment by snowch** [comment]
+1 : this is great!

**Comment by snowch** [comment]
btw - just out of interest, where is the code that handles automatically renewing the session cookie prior to it expiring?

**Comment by ricellis** [comment]
Until #22 is resolved Basic Auth is enabled in parallel to the cookie auth so as per https://github.com/cloudant/java-cloudant/issues/2#issuecomment-55075122 when a request is made with an expired cookie the Basic Auth is used and an updated auth cookie is returned.
The longer term plan to resolve #22 is that the basic auth will not be enabled in parallel and a HTTP response interceptor will be used to check for 403 responses and trigger a request for a new cookie, before re-trying the request.

**Comment by ricellis** [comment]
The proposed resolution for cookie renewal for issue #22 is to use something like [this](https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/http/CookieInterceptor.java#L80).

**Comment by snowch** [comment]
Nice.  Thanks @ricellis
