### ISSUE TITLE
Don't build JSON using string operations

### ISSUE THREAD

**Issue by s100** [cloudant/java-cloudant#101]
Building JSON literals using string operations is dangerous. [Database.getIndexDefinition()](https://github.com/cloudant/java-cloudant/blob/a56aa8d7bfd9d8f41e0c2f90446ddb44f94a41f0/src/main/java/com/cloudant/client/api/Database.java#L824) is the first place I spotted this but there may be other examples in this codebase. GSON is a better choice.

**Comment by ricellis** [comment]
Thanks for pointing this instance out. There are some inconsistencies in this library in this respect, but we do use GSON in most places. We will try and get this and any other remaining string uses fixed up.

**Comment by s100** [comment]
Attempting to build valid JSON using string operations instead of a library is dangerous in principle but it is actually the cause of several defects. This line of code:

    database.findByIndex("\"selector\"asdfasdf", Subscription.class);

or this block of code:

    FindByIndexOptions findByIndexOptions = new FindByIndexOptions();
    findByIndexOptions.fields("\"");
    database.findByIndex("{\"type\":\"subscription\"}", Subscription.class, findByIndexOptions);

both bypass the input sanitisation in [Database.getFindByIndexBody()](https://github.com/cloudant/java-cloudant/blob/master/src/main/java/com/cloudant/client/api/Database.java#L1070) and cause it to construct invalid JSON, which is then passed to the Cloudant backend, resulting in:

    {"error":"bad_request","reason":"invalid UTF-8 JSON"}

I see at [line 1108](https://github.com/cloudant/java-cloudant/blob/master/src/main/java/com/cloudant/client/api/Database.java#L1108) you're actually using GSON to parse the selector JSON, but then just discarding the result. It would be better to just use GSON to assemble the object you need directly.

**Comment by ricellis** [comment]
Sorry if I wasn't clear - I completely agree that this is a bad way of doing things! I've added it to a milestone to make sure we get it fixed soon.

**Comment by ricellis** [comment]
@emlaver I noticed there are some instances of building arrays using strings in `Search.java` that should also be corrected.
