### ISSUE TITLE
Cache for database content

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#119]
An in-memory or other cache could offer performance benefits for some client use cases.

**Comment by mikerhodes** [comment]
This is branch [java-cloudant/feature-119-cache](https://github.com/cloudant/java-cloudant/compare/feature-119-cache).

**Comment by ricellis** [comment]
PRs #181 and #198 enabled easier extension of the `Database` class, which provides an integration point that could be utilized by a cache such as that proposed in branch java-cloudant/feature-119-cache. Closing as the actual cache can be delivered by a separate binary/project.
