### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#140]
There is not much information about logging for this library. We should at the very least document how to enable what logging is available and probably add some additional logging where we think it could be useful.

An example `HttpConnectionInterceptor` for logging HTTP requests and responses would be useful.

**Comment by hubbins** [comment]
Agreed.  I have request that's failing occasionally and I have no way, that I know of, to know the failing URL.  All I can get is a stack trace and the exception message.

**Comment by rchamarthy1** [comment]
Anything being done about this request? I would like to get logs from cloudant-client version 2.2.0. Can you please provide steps on how to enable the logging levels?

Thanks

**Comment by hubbins** [comment]
I checked out a snapshot of 2.2.0 and added slf4j and added my own logging method calls so it could be integrated into our existing application logs.  Ideally, this library would have slf4j support and much more logging built in.  However, what I did was very specific to tracking down our own application issues and isn't meant as a general solution.

**Comment by ricellis** [comment]
The library currently uses `java.util.logging` - I've opened PR #205 that adds some information about enabling the logging. I agree there need to be more logging statements added as well.

**Comment by rchamarthy1** [comment]
Thanks for your replies.

Any idea would the next cloudant-client version (2.3.0?) be added with more logging?

**Comment by ricellis** [comment]
2.3 is already released.
@hubbins @rchamarthy1 Do either of you have any examples of what specific additional logging you were looking for or would be useful to you to help guide what improvements to make?

It sounds like URLs would have been useful, which can already be logged if you use a property like
`-Djava.util.logging.config.file=/path/to/props.file`
pointing to a properties file like this:
```
handlers=java.util.logging.ConsoleHandler
# ensure the ConsoleHandler will log ALL
java.util.logging.ConsoleHandler.level=ALL
# set level to ALL for all Loggers
.level=ALL
```
By setting the `ALL` level for all loggers the JVM's `HttpURLConnection` logging will be included (in this case to `System.err`. You can also find out your JVMs specific implementation to just enable that logger.
