### ISSUE TITLE
 Pagination that enables stateless sessions

### ISSUE THREAD

**Issue by bennyhal** [cloudant/java-cloudant#145]
I am trying to port out java code to the JAVA client 2.0.0 release.

I am trying to find something equivalent to the old style view.queryPage()

This let me get a page and send a param back to the UI for getting the next and previous page. Then when the UI requires the next page it could be retrieved directly using the params originally sent to the UI. This made the server side session stateless.

In 2.0.0 it seems that I need to keep the ViewResponse<K,V> in the session until the UI requests for the next page....

This makes all our sessions state-full, which we want to avoid......

**Comment by ricellis** [comment]
I'm pretty sure I understand, but I've got a few questions just to be really clear:

1. You are passing the `page.getNextParam()` string out of the Java application and then returning that string to the Java later?
2. If you do not keep any state when you are using the 1.x API how do you obtain the `View` object when the string is returned into the Java application, do you just create a new `View` object at that time?
3. Also is this an unfiltered view or do you also use any of the view parameters (e.g. `endKey`)?

**Comment by bennyhal** [comment]
See below

**Comment by bennyhal** [comment]
Would be good to implement this for Cloudant query so there is a consistent stateless paging implementation for Lucene and Couch views
This will help us swap between Lucene and Couch views....

**Comment by ricellis** [comment]
Clearly we overlooked this type of stateless case when refactoring the API and I think we should look into adding parameters to support it.

The differences are caused by the Lucene `Search` pagination being managed by the server providing a `bookmark` parameter whilst the (Couch) `View` paging is managed within the client. I'll consider how we might try to unify these approaches from the client perspective.

**Comment by bennyhal** [comment]
Hi there
I just tried this out it is in line with what we need, thx for that

However there is a bug in the code

If I have this start key 
["TENANT_0", 1, 1, "activity"]

then on page 2 it translates it to this start key 
["TENANT_0", 1.0, 1.0, "activity", "Activity_012_3"]

notice the 1 has been converted to a 1.0

From the order point of view the key 
["TENANT_0", 1.0, 1.0, "activity", "Activity_012_3"]
is before the initial start key

So page 2 is giving me the wrong results

Pls advise

thx

Benny
