### ISSUE TITLE
Consistent paging for Lucene queries to View queries

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#159]
Following on from #145 it was pointed out that it would nice to have a consistent paging experience for Lucene queries and the View queries.
As mentioned in https://github.com/cloudant/java-cloudant/issues/145#issuecomment-158069098:

> the differences are caused by the Lucene Search pagination being managed by the server providing a bookmark parameter whilst the (Couch) View paging is managed within the client.

We should consider how we might implement a similar experience using the bookmark token.

**Comment by DamianCummins** [comment]
Hi, just wondering if there is a plan to include this enhancement any time soon?

**Comment by jcamilli** [comment]
Hi Cloudant folks... I am also wondering what the plan is for this enhancement. It would be really great if this could get implemented.

Thank you.

**Comment by ricellis** [comment]
@DamianCummins @jcamilli thanks for the feedback. We don't have immediate plans to do this, but knowing that there is demand for it is very helpful and we will reconsider it when next planning.

**Comment by rchamarthy1** [comment]
Continuing to Damain and Jared posts (I belong to the same team), this requirement is becoming important for us, and would request to consider it for a soon-planning/implementation.

Advance Thanks,
Ravi Chamarthy

**Comment by ricellis** [comment]
While some aspects of the view paging (e.g. being `Iterable`) can be applied to the query paging other aspects are not (e.g. "stateless" paging via  string token). The server currently does not allow for paging backwards from a bookmark token so it is not possible for us to reverse direction in the way we can with a view.

I am tagging this for a future version where it is possible that we can add similar style APIs to the View paging, but the token aspect will not be possible unless the server API changes.

**Comment by ricellis** [comment]
The server API in CouchDB `main` has taken some steps towards [`bookmark` based paging for views](https://github.com/apache/couchdb-documentation/pull/530) but still no unified pagination style across all query types. This isn't going to be resolved here before EOL - we'll revisit over in [IBM/cloudant-java-sdk ](https://github.com/IBM/cloudant-java-sdk/) if there are more changes to facilitate this.
