### ISSUE TITLE
Pagination tokens turn integer parts of complex keys into floats

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#172]
From: https://github.com/cloudant/java-cloudant/issues/145#issuecomment-165070891
 >If I have this start key
>`["TENANT_0", 1, 1, "activity"]`
>
>then on page 2 it translates it to this start key
>`["TENANT_0", 1.0, 1.0, "activity", "Activity_012_3"]`
>
>notice the 1 has been converted to a 1.0 
>
>From the order point of view the key
>`["TENANT_0", 1.0, 1.0, "activity", "Activity_012_3"]`
>is before the initial start key
>
>So page 2 is giving me the wrong results

**Comment by ricellis** [comment]
@bennyhal are you able to test the branch [172-complex-int](https://github.com/cloudant/java-cloudant/tree/172-complex-int)? It looks like the page requests no longer turn int to float in the tests, but they haven't ever returned the wrong results, so it would be good to get some feedback.

**Comment by bennyhal** [comment]
@ricellis yes this fixes the issue, thx

When is the GA for it?

**Comment by bennyhal** [comment]
Yes this fixes the issue

When is the GA for it?

Thx

Benny

**Comment by ricellis** [comment]
I anticipate another release in January.

**Comment by bennyhal** [comment]
Thx 

Do u when this will be released?

Benny

**Comment by ricellis** [comment]
There are a couple more items targeted for the 2.1.1 milestone before the next release. You can track the progress here: https://github.com/cloudant/java-cloudant/milestones/2.1.1

**Comment by ricellis** [comment]
This has now been released in [2.2.0](../releases/tag/2.2.0).
(Note: the 2.1.1 milestone was renamed to 2.2.0 because of semantic version requirements for some of the changes)
