### ISSUE TITLE
Test Failures against Cloudant Local

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#175]
Internal jenkins server reports failures when running tests against Cloudant Local, see test report http://cloudantsync001.bristol.uk.ibm.com:8080/job/Java-Cloudant%20Nightly/CouchFlavour=cloudantlocal/lastCompletedBuild/testReport/

**Comment by ricellis** [comment]
After merging #180 there appear to be two remaining groups of failures:
i) Some tests fail because the client cannot deserialize an array sequence id (it expects a String)
ii) Tests that use the `_replicate` endpoint are failing with 404 database not found.

**Comment by ricellis** [comment]
As expected the group ii failures have been resolved by creating the `_replicator` database.

**Comment by ricellis** [comment]
This was fixed by #227
