### ISSUE TITLE
Easier generation of selectors

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#184]
It would be nice to have an easier way to generate `Selector` JSON.
Currently the JSON string is either composed or serialized from a `Map` or some other object.

The discussion in #137 proposed some ideas, such as a DSL or some specific helper object for exposing the available options.

**Comment by rhyshort** [comment]
Since it's going to be a lot of work to create a DSL, We could just recommend in the interim that users use groovy to build up `Map` objects which we could adapt our API to accept. See http://groovy-lang.org/groovy-dev-kit.html#Collections-Maps.
