### ISSUE TITLE
Updating attachment fails in 2.2.0

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#190]
There is a regression in release 2.2.0 where updating an attachment builds an incorrect URL causing a `CouchDbException` to be thrown.

The method `com.cloudant.client.api.Database#saveAttachment(java.io.InputStream, java.lang.String, java.lang.String, java.lang.String, java.lang.String)` eventually uses the new `DatabaseURIHelper` which is incorrectly making the revision part of the path instead of adding it as the `rev` query parameter.

**Comment by dlandis** [comment]
I was just about to report this too. It is not just updating an attachment but also adding a new attachment to an existing document which fails.

**Comment by dlandis** [comment]
@ricellis  Do you think it is a valid workaround to save the new attachment first and then add the document afterwards based on the returned id and rev from the attachment? Unfortunately this is a blocker for us and don't want to revert to pre-2.x version.

**Comment by ricellis** [comment]
@dlandis 
The fix I did for the revision parameter should also fix the case of adding a new attachment to an existing document. I've written an extra test case for that scenario in PR #192 does that cover your problem?

**Comment by ricellis** [comment]
Fixed in #191 and additional test in #192 .

**Comment by dlandis** [comment]
That covers my problem. Thanks
