### ISSUE TITLE
ViewRequestBuilder has hidden stale functionality

### ISSUE THREAD

**Issue by stephen-kruger** [cloudant/java-cloudant#194]
My code currently uses getView(...) to execute a view. All works fine.

However if I then introduce vrb.stale(SettableViewParameters.STALE_OK); my unit tests fail, since the results from my data population are not "ready" - this is expected.

However i then toggle to use vrb.stale(SettableViewParameters.STALE_UPDATE_AFTER);
And this is where the issue arises. My vew still continues to fail to give results.
If I comment out entirely the call to stale(...) the view starts giving results again.

So t appears merely invoking the stale(...) method has some irreversible implications for the view, regardless of which parameter you pass it.

Currently using 2.2.0, but saw the same behavious with previous versions as well.

**Comment by ricellis** [comment]
There are 3 possibilities here:

| stale parameter | outcome | Java |
| ---- | ---- | ---- |
| `stale=ok` | Allow stale views. | `vrb.stale(SettableViewParameters.STALE_OK)`
| `stale=update_after` | Allow stale views, but update them immediately after the request. | `vrb.stale(SettableViewParameters.STALE_UPDATE_AFTER)`
| No stale parameter (default) | Do not allow stale views | no `stale` method call or `vrb.stale(null)`

`STALE_OK` and `STALE_UPDATE_AFTER` both allow stale documents. If you do not want to allow stale documents you don't want to call the `.stale()` method at all (as you've observed by commenting it out). If you wanted to re-use a `ViewRequestBuilder` where stale had previously been set you could call `.stale(null)` to remove the parameter and disallow stale results.

**Comment by stephen-kruger** [comment]
That makes sense - many thanks for the explanation.
However coding this is pretty funky.
Would it be possible to add in a SettableViewParameters.STALE_NO constant to better inform this third, and very different behaviour?Javadoc could then mention the default setting (and thus behaviour).

I could attempt this patch myself if required.

**Comment by ricellis** [comment]
Yeah, I can see how the default absence of the stale parameter can be confusing. I guess we didn't anticipate toggling between stale/fresh using the same `ViewRequestBuilder` either, which makes it more so.

Thanks, we'd be happy to look at a PR for an additional constant and the associated javadoc updates. It would also be good to include an additional test, but I don't think this would need to actually test whether the server returned stale docs or not, I think a mock that validates the parameter (or absence of) on the request would be sufficient. If that's asking too much please feel free to do what you can and we'll try to fill in the rest.

You will need to do a CLA first though, please see the [contributing doc](https://github.com/cloudant/java-cloudant/blob/master/CONTRIBUTING.md) for guidelines.
