### ISSUE TITLE
Handle cases where maximum URL length is exceeded

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#196]
Some requests can generate extremely long URL query strings. For example an `_all_docs` request with a long list of keys. If the URL generated for a request exceeds a certain length then a `400 BAD REQUEST` could result (not sure why we don't always see a `414`).

There are two workarounds for this:
1. Make multiple requests with fewer query arguments (possible for an `_all_docs` with many keys, but may not be applicable to some queries)
2. Use `POST` instead of `GET` and supply the query parameters as a JSON body (may not be acceptable for all endpoints).

Note that the version 1.x clients did `POST` for cases where keys were supplied to an `_all_docs` request, but did not generally handle long URLs. It would be best if we could handle all long URL cases gracefully.

**Comment by ricellis** [comment]
In addition to the workarounds described above for non-`_all_docs` views is to use the `ViewMultipleRequest` to force a POST avoiding the URL length limit e.g.
```java
        // Single request - fails because URL to long during GET
        ViewRequest<String, Object> vRequest = db.getViewRequestBuilder("exampleddoc", "exampleview")
                .newRequest(Key.Type.STRING, Object.class)
                .keys(aReallyLongArrayOfKeys)
                .build();
        ViewResponse<String, Object> vResponse = vRequest.getResponse();

        // Multi request, but with only 1 query - forces a POST
        ViewMultipleRequest<String, Object> mRequest = db.getViewRequestBuilder("exampleddoc", "exampleview")
                .newMultipleRequest(Key.Type.STRING, Object.class)
                .keys(aReallyLongArrayOfKeys)
                .add() // Add called only once for a single request
                .build();
        List<ViewResponse<String, Object>> mResponses = mRequest.getViewResponses();
        ViewResponse<String, Object> mResponse = mResponses.get(0); // There will be only 1 response
```

**Comment by tomblench** [comment]
Merged to master; closing
