### ISSUE TITLE
Ask the server for uuids instead of generating our own.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#201]
Currently the library generates it's own UUID when a document doesn't have an ID set, we should defer to the server for UUIDs. In order to reduce the number of requests sent to generate UUIDs we should ask for a block of UUIDs and use them until the list runs out.

**Comment by davidl2** [comment]
I agree that such an option would be nice for situations where one is
paranoid about the local source of randomness, but I don't think it should
be the default. It's an extra RTT, right? Also, it would be nice to have
pluggable local-unique-ID generators.

**Comment by ricellis** [comment]
Closing, we won't be changing this here. 
For a [document `POST`](https://www.javadoc.io/static/com.cloudant/cloudant-client/2.19.1/com/cloudant/client/api/Database.html#post-java.lang.Object-) the ID is generated server-side anyway.

Our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) doesn't generate any UUIDs client-side for a [`putDocument`](https://cloud.ibm.com/apidocs/cloudant?code=java#putdocument), a doc id is a required path parameter for that operation and the validation will fail if it is not provided. The expectation is that a user will [`postDocument`](https://cloud.ibm.com/apidocs/cloudant?code=java#postdocument) if they want the server to generate an ID. If for some reason it is desired to `PUT` _and_ have a server generated ID then the [`getUuids`](https://cloud.ibm.com/apidocs/cloudant?code=java#getuuids) operation is available.
