### ISSUE TITLE
Configure Proxy

### ISSUE THREAD

**Issue by FS1360472174** [cloudant/java-cloudant#208]
Cloundant Client 2.1.0 version.
Configure Proxy like this:
client = ClientBuilder.url(new URL(url)).username(username).password(password).proxyURL(new URL(proxy_url)).build();

proxy server is fiddler 127.0.0.1:8888.found request in fiddler,but got response code 408.
and got exception in eclipse console.

so,i want to know is this a bug in client2.1.0

**Comment by ricellis** [comment]
@FS1360472174 can you please clarify if the `408` timeout was returned by Cloudant to the proxy and then to the client or whether it was just returned by the proxy server?

**Comment by FS1360472174** [comment]
@ricellis  I catch the 408 timeout in fiddler,which is he proxy server.
so 408 timeout was returned by Cloudant to the proxy and then to the client.
I mean proxy server do post the request to server.

**Comment by ricellis** [comment]
I haven't seen any other reports of this. Can you give us an example of what code you are using when you are getting the `408`?

**Comment by ricellis** [comment]
Closing as there has been no further discussion, please re-open if necessary.
