### ISSUE TITLE
DesignDocument Class requires Documentation

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#213]
- Version: All 
- Java Version: N/A

Currently the `com.cloudant.api.model.DesignDocument` class has zero documentation.
Each property getter/setter should have documentation that explains what the field is for, what happens if the field is not set e.g. Is there a default, if so what is it. What values are accepted if restricted, etc. This will make the `DesignDocument` class easier for new comers to work with.

**Comment by ricellis** [comment]
@rhyshort I've made a pass at this, see #248.
There aren't any defaults for any of these properties in the client and there is no client side validation beyond the typing of arguments so it is pretty difficult to meet the requirements of your description. I have however added links to the appropriate Cloudant docs so I think that gets most of what you want.
