### ISSUE TITLE
HTTP interceptors should be able to indicate failure/stop processing

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#216]
HTTP Interceptors should be able to indicate a failure and stop http request processing, this could take the form of throwing a specified checked exception, or returning `null`. I think the preferred option would be to allow returning null for now, and make the API breaking change to enable throwing exceptions as part of 2.0.

**Comment by ricellis** [comment]
They already throw an unchecked `com.cloudant.http.interceptors.HttpConnectionInterceptorException`.

**Comment by rhyshort** [comment]
Ah okay, I guess this is where the difference between sync-android and java-cloudant come to bare.
