### ISSUE TITLE
Cloudant Java Client failing with '400 Bad request' error

### ISSUE THREAD

**Issue by jponth** [cloudant/java-cloudant#229]
Description of issue:
In order to connect to Cloudant Local, had to put in username:password@ in the url and also basic authenticator.If only one of the above is provided, access to cloudant db fails with  '400 Bad request' error. See code below

- CloudantClient (java-cloudant) version(s): 2.3
- Java version: 1.8, redhat linux
- If you're using the optional okhttp dependency: no

Code sample:
1. What didn't work:
			CloudantClient client =  ClientBuilder.url(new URL("ip.address:80"))
			              .username("username")
			              .password("password")
			              .build();
2. What worked:
Note the username:password in the url.
			BasicAuthInterceptor basicAuthInterceptor = new BasicAuthInterceptor("username" + ":" + "password");
			CloudantClient client =  ClientBuilder.url(new URL("username:password@ip.address:80"))
			              .username("username")
			              .password("password")
			              .interceptors(basicAuthInterceptor)
			              .build();

**Comment by rhyshort** [comment]
What version of Cloudant Local are you using? Also is it configured to [require authorised user](http://docs.couchdb.org/en/1.6.1/config/auth.html#couch_httpd_auth/require_valid_user)?

**Comment by jponth** [comment]
Using Cloudant Local version 1.0.0.3. Yes, require authorized user.

Cloudant-client 2.3, for Java

Thanks

**Comment by ricellis** [comment]
Thanks for the information. The `require_valid_user=true` option prevents any endpoint (including the `_session` endpoint for getting a cookie) being accessed without already being authenticated. This means authentication needs to happen by another method, before the client can get a cookie. As you have identified adding a `BasicAuthInterceptor` is one way of ensuring the request for a cookie is authenticated, although I wouldn't have expected the URL to need credentials as well so we will investigate.

**Comment by jponth** [comment]
We hadn't expected the URL to include the credentials. Something is not right. Thanks for investigating.
Btw, after getting the connection working, we were able to assert the existing document, by using db.contains("<id>") method. But when we attempted to use db.findByIndex("{ "selector": { "studyID": "s12345", "siteID": "si1234", "username": "vsinha" } }"), we are getting the  following error, java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY. We also tried without the outer { } in the above string. Wondering if there is mismatch between the cloudant.local and cloudant-client versions.

Here is the stacktrace:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
 at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
 at com.google.gson.Gson.fromJson(Gson.java:795)
 at com.google.gson.Gson.fromJson(Gson.java:761)
 at com.google.gson.Gson.fromJson(Gson.java:710)
 at com.google.gson.Gson.fromJson(Gson.java:682)
 at com.cloudant.client.api.Database.getFindByIndexBody(Database.java:1188)
 at com.cloudant.client.api.Database.findByIndex(Database.java:380)
 at com.cloudant.client.api.Database.findByIndex(Database.java:342)
Thanks a lot!John

**Comment by jponth** [comment]
Earlier in my response, to the question, 'Also is it configured to require authorised user?' I had responded 'Yes, require authorized user.'  Actually, require_valid_user has been false, all along. 

 The error 'java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1' is being opened as new issue.
Thanks for your help.

**Comment by ricellis** [comment]
Note discussion for `java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY` issue has moved to #232.

**Comment by jponth** [comment]
It was confirmed and verified that after upgrading GSON to version 2.2.4, connect using ClientBuilder.url() worked without providing credentials in the url.
Thanks for you help
John

**Comment by ricellis** [comment]
Glad the problem is resolved. We recommend using Maven or Gradle for dependency management as they automatically get the correct dependency versions.
