### ISSUE TITLE
MapReduce querying does not work from java but works from cloudant dashboard 

### ISSUE THREAD

**Issue by gowthamravichandran** [cloudant/java-cloudant#231]
I created a view from cloudant dashboard, like the following code

`function (doc) {
  if(doc.type=="USER"){
    for(var i=0;i<doc.apiKeyList.length;i++){
  emit([doc._id,doc.apiKeyList[i].deviceId, doc.apiKeyList[i].apiKey],null);
    }
  }
}`

And I queried from the dashboard by selecting By Key(s) from options menu like this.

`[["docId","devId","keyId"]]`

This works perfectly fine and returns me only desired record.
But when I try querying the same view from Java, 

`List<UserDTO> userDTOList = db.getViewRequestBuilder("deviceApiKeyDD", "device-apikey-view")
    .newRequest(Key.Type.STRING,Object.class).includeDocs(true)
    .keys("[\"docId\",\"devId\",\"keyId\"]").reduce(false)
    .build().getResponse()
    .getDocsAs(UserDTO.class);`

I get a empty list always.

I also tried giving the same data with start key and end key, but it lists me all the documents in the database that are in the same pattern (which is not desired).

I also tried enclosing the key with another set of square brackets in java, but no luck

I am not sure whether there is something wrong with my code or API.

Can someone help with this.?

**Comment by ricellis** [comment]
Your key appears to be an array (also known as a complex key), but you have used `Key.Type.STRING` in your request.
For a complex key you need to use `Key.Type.COMPLEX` and build the key you want e.g.
```java
List<UserDTO> userDTOList = db.getViewRequestBuilder("deviceApiKeyDD", "device-apikey-view")
                        .newRequest(Key.Type.COMPLEX,Object.class)
                        .includeDocs(true)
                        .keys(Key.complex("docId", "devId", "keyId"))
                        .reduce(false)
                        .build()
                        .getResponse()
                        .getDocsAs(UserDTO.class);
```

**Comment by gowthamravichandran** [comment]
Wow!!! That solved the issue... Thanks a lot @ricellis
