### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY

### ISSUE THREAD

**Issue by jponth** [cloudant/java-cloudant#232]
Attempted to use db.findByIndex("{ "selector": { "studyID": "s12345", "siteID": "si1234", "username": "user" } }"), we are getting the  following error, java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY. We also tried without the outer { } in the above string. Using Cloudant.Local and cloudant-client for Java

- CloudantClient (java-cloudant) version(s): 2.3
- GSON: 2.2.2
- Java version (including vendor and platform). 1.8.0_71, Linux OS 2.6.32, Apache Tomcat 6.0.24
- If you're using the optional okhttp dependency: No
- A small code sample that demonstrates the issue: See below

Btw, after getting the connection working, we were able to assert the existing document, by using db.contains("<id>") method. But when we attempted to use db.findByIndex("{ "selector": { "studyID": "s12345", "siteID": "si1234", "username": "user" } }"), we are getting the  following error, java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY. We also tried without the outer { } in the above string. Wondering if there is mismatch between the cloudant.local and cloudant-client versions.

Here is the stacktrace:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
at com.google.gson.Gson.fromJson(Gson.java:795)
at com.google.gson.Gson.fromJson(Gson.java:761)
at com.google.gson.Gson.fromJson(Gson.java:710)
at com.google.gson.Gson.fromJson(Gson.java:682)
at com.cloudant.client.api.Database.getFindByIndexBody(Database.java:1188)
at com.cloudant.client.api.Database.findByIndex(Database.java:380)
at com.cloudant.client.api.Database.findByIndex(Database.java:342)

**Comment by ricellis** [comment]
Our dependency tree has GSON 2.2.4 which is what is tested.

**Comment by jponth** [comment]
We upgraded the GSON to version 2.2.4  and the issue was resolved.
Thanks for helping with this !

**Comment by rhyshort** [comment]
Great to hear that's fixed.
