### ISSUE TITLE
PATCH support for document update

### ISSUE THREAD

**Issue by sagardiwan** [cloudant/java-cloudant#236]
We are trying to find if PATCH type requests are supported by the library.

Normally, we first read a document and after making appropriate changes, we send an update request. 

We are looking for a way to directly update any particular value. So as the client, we need not get the document and update, instead we can just specify the particular property value to be updated and the library would internally handle lookup and update cloudant document.

Is this feature supported ?

**Comment by rhyshort** [comment]
Unfortunately CouchDB does not support the HTTP `PATCH` method to update documents, for details on the CouchDB API see their [documentation](http://couchdb.readthedocs.org/en/1.6.1/api/document/common.html)
