### ISSUE TITLE
Error 'Invalid key use_index' returned when querying against Cloudant-0.1.0-local

### ISSUE THREAD

**Issue by gsonal** [cloudant/java-cloudant#243]
The Cloudant query API call, implemented using java-cloudant's "cloudant-client" classes, runs successfully against the Cloudant version 1.0.2 (if db exists on cloudant.com), but same API call fails against the local installation of Cloudant (db version 0.1.0-local).

**Steps followed**:
1) Created an index using POST http call for ` /_index` endpoint
2) Invoke a cloudant query using the Database.findByIndex(String selectorJson, Class<T> classOfT) method:
`db.findByIndex("\"selector\": {\"docType\": {\"$eq\": \"person\"}}",Person.class)`
3) Error returned: "com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: invalid_key: Invalid key use_index for this request."

**Root cause identified**:
FindByIndexOptions class initializes the useIndex attribute by default ( `private JsonArray useIndex = new JsonArray()` ) therefore the generated query body contains "use_index" parameter even when no explicit index is provided.

**Comment by ricellis** [comment]
Thanks for reporting this, it looks like it has been a problem since 2.2.0 when we changed the `String` to an `JsonArray`, but didn't add an empty check to the `null` check for adding the `use_index` property to the request.
Looking at this in detail we shouldn't be using a `JsonArray` for the single design document case either, which should be a `String` so there are a couple of fixes to be done here.

**Comment by gsonal** [comment]
Thanks for accepting and fixing it immediately. Based on the releases page, it seems every month there is a release done. Does that mean the milestone 2.4.3 will be out in May 2016?
When will the upgraded api jars be available on Maven_repo?

**Comment by rhyshort** [comment]
We don't commit to a monthly release cycle, we tend to make releases when we think they are ready. It has generally been a coincidence that releases have happened approximately once per month. If your subscribed to the repo (by clicking watch) you should get notified when the release happens.
