### ISSUE TITLE
Http Connection Re-use without okHttp

### ISSUE THREAD

**Issue by sagardiwan** [cloudant/java-cloudant#247]
We plan to use the client in WebSphere Liberty, without including the okHttp library. I believe the library would use default JVM httpurlconnection in this case. We also require that the connections remain open  and reused.

We ensured that keep.alive and max.connections system properties are appropriately set.

However the connection somehow gets closed immediately after a read and write. 

Is there a specific setting or property needed to keep the connections open ?

**Comment by ricellis** [comment]
There are no pooling settings/properties in java-cloudant itself when using the `HttpURLConnection` the settings are at the JVM level.

The JVM properties are `http.maxConnections` and `http.keepAlive`[[1]](http://docs.oracle.com/javase/8/docs/technotes/guides/net/http-keepalive.html) (although sometimes documented as `http.keepalive`[[2]](http://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html) I found it to be case sensitive and only `http.keepAlive` worked on my JVM).

It is also worth noting that these properties are only checked at JVM startup, but typically default to values of `5` and `true` respectively so pooling should be on with 5 connections (per destination) by default, but I guess the defaults may vary by JVM.

**Comment by sagardiwan** [comment]
Thanks for pointing out this case sensitive nature. Tried both "http.keepAlive" and "http.keepalive" , however no luck yet. The socket somehow gets closed. Will need to check the behavior with a different JVM. Will try to update as soon as we try out this.

**Comment by ricellis** [comment]
What read/write are you doing and with which version of java-cloudant?
I believe there are some conditions under which the JVM is not able to re-use connections (for example for unknown content length or if large response streams are not consumed). The database server is also able to close the connection from its side (although I think the timeout for this is 2.5 minutes). There may also be additional considerations if you have a proxy.

**Comment by sagardiwan** [comment]
It is currently used in 2 separate applications or scenarios -
1) Version 2.2.0 used in an application, where the operations are always bulk updates 
2) Version 2.4.2 used in a scenario where operations are save, find and update (always single document at a time)

In both cases the behavior is same, that the connection is closed after a thread completes the operation. The client is used as singleton.

**Comment by ricellis** [comment]
The management of these connections is handled entirely by `HttpURLConnection` and is outside of the control of java-cloudant.

I have run with `HttpURLConnection` logging enabled and I can see the connections being re-used for a scenario with `save` then `find` then `update`. I can also see the connections continue to be re-used if subsequent operations are within 5 seconds. It appears that this is the [JVM's default connection eviction time](http://stackoverflow.com/questions/5019617/does-java-http-connection-pool-have-an-eviction-time-can-it-be-set). I cannot find an option to configure this although it may depend on your JVM.

**Comment by sagardiwan** [comment]
Thank you for the investigation. I think the "connection eviction time" explains the behavior we are seeing. I ran more tests and notice that the connection does stay alive for few seconds, to be precise about 10 seconds before it is closed. 

I have attached a screen shot of the packet capture (hiding the destination ip). As you can see, the FIN sequence consistently begins after 10 seconds of transaction. 

![cloudant-packet](https://cloud.githubusercontent.com/assets/17622591/14822160/7cdf0d26-0b9b-11e6-8706-05ae02acf2fb.jpg)

Thanks for the investigation though, this seems to be subject to the JVM.
