### ISSUE TITLE
NoDocumentException is not raised with non existing and not to be created databases

### ISSUE THREAD

**Issue by ptommasi** [cloudant/java-cloudant#258]
`com.cloudant.client.api.CloudantClient.database(dbName, create)` method doesn't raise anymore a `com.cloudant.client.org.lightcouch.NoDocumentException` exception. In the chain of calls, it seems to be related to the constructor `com.cloudant.client.org.lightcouch.CouchDatabaseBase.CouchDatabaseBase(CouchDbClient, String, boolean)`, which doesn't raise that exception anymore (compared to java-cloudant version 1.0.0).

In version 1.0.0, class `org.lightcouch.CouchDatabaseBase.CouchDatabaseBase(CouchDbClientBase, String, boolean)` had a `connect()` method which was  raising `NoDocumentException`, now it has been substituted with a `create()` which has a different logic.

- CloudantClient (java-cloudant) version(s) that are affected by this issue: for sure 2.4.2 and 2.4.3 (version 1.0.0 is not affected)
- Java version (including vendor and platform): Oracle JDK 1.7
- If you're using the optional okhttp dependency: no
- A small code sample that demonstrates the issue:

```java
public Database getDB(String dbName, boolean create) {
		try {
			return client.database(dbName, create);
		} catch(NoDocumentException e) {
			// NEVER CALLED!
			log.debug("Database " + dbName + " doesn't exist and won't be created: " + e.getMessage());
			return null;
		}
}
```

A workaround (at the cost of one more GET request) is:
```
public Database getDB(String dbName, boolean create) {
		try {
			Database result client.database(dbName, create);
			result.info();
			return result;
		} catch(NoDocumentException e) {
			// NEVER CALLED!
			log.debug("Database " + dbName + " doesn't exist and won't be created: " + e.getMessage());
			return null;
		}
}
```

**Comment by rhyshort** [comment]
Hi, thanks for reporting this. The behaviour is as expected, the documentation hasn't been updated to reflect the change we made.  You will get the `NoDocumentException` when you make your first request against the database instance as you noticed through your workaround. We'll get the documentation updated and included in the 2.5.0 release.

**Comment by ptommasi** [comment]
There is a more performant / elegant way to know if a database exists or not? In my logic I first check if a database exists (and I handle many of them) and then, if not, I create it and init with few custom design documents and slow to be created data. A simple check (eg: database.exists() or something like that) would be handy!

**Comment by ricellis** [comment]
Most use cases we've seen are looking for _ensure exists_ behaviour. That is they want to be sure a database exists before they try to interact with it. This is covered by the method call `client.database("exampledbname", true)`. The alternative `client.createDB("exampledbname")` *should* throw a `PreconditionFailedException` if the database already exists. Unfortunately that `PreconditionFailedException` doesn't make it out at the moment and that needs to be fixed as part of this issue.

In any case there are quite a few different ways of doing this, providing some different options between the types and numbers of requests being made:

```java
Database db;
// 1. ensure exists
db = client.database("example", true);
// db will always exist now, but no easy initialization route for your use case
// Single PUT request only

// 2. make a request (i.e. your workaround)
db = client.database("example", false);
try {
  db.info();
} catch (NoDocumentException e) {
  // Didn't exist, create and initialize
  db = client.database("example", true);
  // initialize
}
// Single GET, additional PUT if didn't exist

// 3. Use createDB (once the fix is delivered)
db = client.database("example",  false);
try  {
  client.createDB("example");
  // initialize
} catch (PreconditionFailedException e) {
  // Already existed
}
// Single PUT request only, with a branch for the already exists case

//4. Make a HEAD request
db = client.database("example", false);
try {
  client.executeRequest(Http.HEAD(db.getDBUri()));
} catch(NoDocumentException e) {
  // Didn't exist, create and initialize
  db = client.database("example", true);
  // initialize
}
// Single HEAD request, additional PUT if didn't exist
```

**Comment by ptommasi** [comment]
Hi @ricellis , I like the fourth variant, since an HEAD is faster than a GET, and I'll move to the third option once the fix is delivered! Thanks!
