### ISSUE TITLE
Provide public API for findIndexByStream

### ISSUE THREAD

**Issue by Kronos11** [cloudant/java-cloudant#266]
We have been using Cloudant API version 1.2.3 for quite a while now. One of the features we used was the HttpClient to get a direct connection, call the _find and get the raw json back from Cloudant. In this case we were simply returning the json back to the client to be added to a simple table. There was no need to use the API because we didn't want to serialize anything because we would just have to deserialize it again later anyway...
Looking to upgrade to API 2.5 we realize this HttpClient was removed as well as executeRequest in the client API, so now if we want the same functionality we have to use another HttpClient and wire up everything manually.

What would be much better is if we could have a new function that returns a stream much like find already does. This would allow us to upgrade sooner and not have to build in code that is unecessary.

**Comment by Kronos11** [comment]
I apologize I did find that executeRequest is still in the client, however this would still be a nice feature.

**Comment by ricellis** [comment]
Thanks for the feedback, you are correct the way to do this in 2.x is to use `executeRequest` e.g.
```java
// Construct find URL for the database
URL findUrl = new URL(db.getDBUri().toString() + "/_find");
// Build a POST request
HttpConnection findRequest = Http.POST(findUrl, "application/json");
// Set the body wih the JSON required for the query
findRequest.setRequestBody("{\"selector\": {\"year\": {\"$gt\": 2010}}}");
// Execute the request
HttpConnection findResponse = client.executeRequest(findRequest);
// Get the response as a stream from the response HttpConnection
try (InputStream response = findResponse.responseAsInputStream()) {
  // Do something with stream
}
```

Ultimately I think the library should be restructured in a way that allows any response to be consumed as a stream, a JSON object, or mapped POJO as desired by the caller. I think the API you would like would fit into that model, albeit not under a specific new `findIndexByStream` API, but as a standard pattern for any response.

**Comment by ricellis** [comment]
We're not doing enhancements here. However, our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) includes streaming versions of operations, including [`postFind`](https://cloud.ibm.com/apidocs/cloudant?code=java#postfind), called `postFindAsStream`.
