### ISSUE TITLE
selector API takes JSON fragment only?

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#27]
The `findByIndex()` API takes a 'selector' which the [query docs](https://docs.cloudant.com/api/cloudant-query.html#cloudant-query-selectors) give as a JSON object such as 
```
{"name": "Paul"}
```
however the [README](https://github.com/cloudant/java-cloudant#cloudant-query) gives the example:
```
List<Movie> movies = db.findByIndex("\"selector\": 
                { \"Movie_year\": {\"$gt\": 1960}, \"Person_name\": \"Alec Guinness\" }",
```
.. where the selector is more of a "fragment" than a well formed object. In fact, I found that the server returned JSON errors unless I called `findByIndex` with  `"\'selector\':" + someJson` (where `someJson` is the well formed JSON selector body). 

Could this API be clarified, or even better accept just the JSON body and not require the key? Otherwise it is awkward to create this "Fragment" for use with the API.

**Comment by mariobriggs** [comment]
@srl295 thanks for bringing this to our notice.  I agree with you that the selectorJson argument should have taken just the JSON body (my bad) . We need to roll a fix and take care of backwards compat (in case there are user's who are already using by supplying the key)

**Comment by srl295** [comment]
@mariobriggs welcome! I would think you could detect the "current" case by something like this:
 `selector.trim().startsWith("'selector':")||selector.trim().startsWith("\"selector\":")`

**Comment by mariobriggs** [comment]
fixed in branch vNext. Give it a spin. Test case added in IndexTests

**Comment by srl295** [comment]
Looks good, thanks!

**Comment by mariobriggs** [comment]
pushed out in 1.0.1 release
