### ISSUE TITLE
Warn / log if DNS TTL is long/infinite

### ISSUE THREAD

**Issue by willholley** [cloudant/java-cloudant#270]
When debugging connection issues, it would be useful to know the DNS caching policy. Perhaps we could log the value of `java.security.Security.getProperty("networkaddress.cache.ttl");` when the library is initialised?

**Comment by ricellis** [comment]
On thing to consider is that calling `Security.getProperty` is itself restricted by a `SecurityPermission`. [[1]](https://docs.oracle.com/javase/7/docs/technotes/guides/security/permissions.html#SecurityPermission)

So in the case where a `SecurityManager` is active (the most likely scenario for an infinitely cached DNS entry) we may not have access to read the value anyway and would need to handle the security exception.
