### ISSUE TITLE
CookieInterceptor should not try to renew with invalid credentials

### ISSUE THREAD

**Issue by ricellis** [cloudant/java-cloudant#273]
- CloudantClient (java-cloudant) version(s) that are affected by this issue.
    * 2.x
- Java version (including vendor and platform).
    * Any
- If you're using the optional okhttp dependency.
    * N/A
- A small code sample that demonstrates the issue.

```java
CloudantClient client = ClientBuilder.account("example")
    .username("user")
    .password("wrong")
    .build();
client.getAllDbs(); // make any request
```

Using the wrong credentials results in this log output:

>Jul 21, 2016 11:14:31 AM com.cloudant.http.interceptors.CookieInterceptor getCookie
SEVERE: Credentials are incorrect, cookie authentication will not be attempted again by this interceptor object
Jul 21, 2016 11:14:32 AM com.cloudant.http.interceptors.CookieInterceptor getCookie
SEVERE: Credentials are incorrect, cookie authentication will not be attempted again by this interceptor object

Currently the code attempts to `getCookie` as the request is made and when the response is received (for renewal scenarios). In this case since we know the credentials are wrong there is no value trying to get the cookie again in the response.

There may be some value in throwing the exception from the `CookieInterceptor` to indicate the credentials failure earlier, but since the `CookieInterceptor` is always present in the chain allowing it to cause a request to fail earlier could interfere in scenarios where it is merely a bystander to some other authentication interceptor further down the chain so this would need some careful consideration.

**Comment by developpef** [comment]
Hello,
I faced this error, using v2.6.0 or greater... What could I do?  
Thanks

**Comment by ricellis** [comment]
@developpef please double check that your credentials are correct and if you still see the problem on version 2.7.0 then please raise a new issue.

**Comment by developpef** [comment]
Yes sorry I solved the issue : I was using wrong credentials. I needed to generate an API access key. Thank you for your answer.
