### ISSUE TITLE
CloudantClient (java-cloudant)  2.5.1 Query with multiple key does not return any document

### ISSUE THREAD

**Issue by patelni** [cloudant/java-cloudant#274]
Hi I am trying to Query cloudant view by using

Cloudant-client version 2.5.1
I have included okhttp dependency,my Java version 1.8

Here is my sample code

ViewResponse<String, String> response = db.getViewRequestBuilder("views","myViewName").newRequest(Key.Type.STRING, String.class).includeDocs(true) .keys("testUser", "testDepartment")  .reduce(false) 				         .build().getResponse();

Even though I have document in cloudant containing fields with values like "userName": "testUser" and "department:"testDepartment".

This code does not return any document. If I remove .keys() it will return all the documents.

Please help.

Thank you.

**Comment by ricellis** [comment]
@patelni 
It looks like you are trying to query keys from multiple properties of the document. Are you emitting an array (complex key) from your view's map function?
Something like:
```javascript
emit( [doc.userName, doc.department] )
```

**Comment by patelni** [comment]
Hi Rich, 
Thank you for looking at my  issue.
yes, I am trying to query from multiple properties.
below is the code for my view.

function(doc) { 
  if ( doc.userName && doc.department ) { 

    emit( [ doc.userName,  doc.department ],  doc);

  }
} 

Since, you have mentioned about complex key, I am not sure if my code for querying view is right?
Can you please provide some guidance, how can I write a code for querying above view?

Thank you.

**Comment by ricellis** [comment]
Issue https://github.com/cloudant/java-cloudant/issues/231 was similar and has an [example](https://github.com/cloudant/java-cloudant/issues/231#issuecomment-195401511) of querying with a complex key.
For your case the key would be:
`Key.complex("testUser", "testDepartment")`

I see that you are emitting the entire `doc` as the value in your map function's key/value pair. This is unnecessary and will end up duplicating the document contents in your map. As you have already shown in your query there is an `includeDocs` option for getting the entire document content returned from a query of a view. 
If you don't need to map to a particular value then you could emit `null` or a value of `1` is frequently used for counting etc.

**Comment by patelni** [comment]
Hi Rich,

Thank you so much for your instant response. The above solution worked.
I appreciate your help.

Thank you.
