### ISSUE TITLE
client constructor: clarify user vs api

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#28]
`CloudantClient(String account, String loginUsername, String password)`

* The second parameter here could be documented as "apikey or account" if I understand properly:  "If using an API key, this is the api key, otherwise pass in the account for this parameter also" ?
* Actually, could you take a "null" loginUsername here and then:  `if loginUsername==null { loginUsername = account}` ? Maybe that would be more confusing than helpful, though.

**Comment by mariobriggs** [comment]
By documentation, i am not sure if you referring to the javadoc or Readme. In case of the latter it is written as 'userName or Apikey'. Seems ok to me to change that to what u suggested in first point.

For the 2nd point, ideally would have gone with a overloaded constructor that took just 2 strings (account and password), that signature was taken by the connect-with-cookie constructor :-) . Will wait for  some more ideas/inputs from folks as they start to use.

**Comment by srl295** [comment]
@mariobriggs sort of both. [Readme](https://github.com/cloudant/java-cloudant#getting-started) mentions account, and then userName or apiKey, and then password. Really, sometimes the account is the same as the userName, and sometimes the apiKey is the userName - it makes sense, but was't immediately obvious.  Thanks for looking at it..

**Comment by mariobriggs** [comment]
clarified this in the ReadMe (javadocs - next version release)

**Comment by mariobriggs** [comment]
fixed  javadocs in vNext branch

**Comment by srl295** [comment]
docs look good

**Comment by mariobriggs** [comment]
pushed out in 1.0.1 release
