### ISSUE TITLE
startKey and endKey - filtering a view using a complex key

### ISSUE THREAD

**Issue by rolivieri** [cloudant/java-cloudant#29]
Hello, 
I have a view that returns complex keys that follow this format/pattern:

["1000","2000”,0]
["1000","2000",1]
["1000","2000”,2]
["1000","2001”,0]
["1000","2001”,1]
["1000","2001”,2]
["1001”,”2000”,0]
["1001”,”2000",1]
["1001”,”2000”,2]
["1001”,”2001”,0]
["1001”,”2001”,1]
["1001”,”2001”,2]
...

I can query directly my view [using curl from the command line] by submitting a REST request and specifying the following start and end key values:

startkey=[\"1000\",\"0\",0]&endkey=[\"1000\",{}]"

The above start and end key values return the data I am expecting. Basically, I am filtering the results and getting only those records that have "1000" as the first value in the complex key.

However, when I try to run the same query against the view using the Java API, I don’t get the expected results:
...
Object[] startKeys = new Object[] { "1000", "0", 0 };
Object[] endKeys = new Object[] { "1000", “{}” };
view.startKey(startKeys);
view.endKey(endKeys);
....

I get no results back when using the start and end key values shown above in the Java code. I am wondering if there is a defect in the API code that builds the URL to query and filter the view. Could you provide some guidance on how to resolve this issue? Thanks.

**Comment by mariobriggs** [comment]
I believe the difference between the results is because in the java API case, you use "{}" i.e {} as a string, whereas in your REST request it is not a string. To achieve the same via the Java API, your endKeys definition should be as below

 ```
Object[] endKeys =  new Object[] { "1000", new Object() }
```

**Comment by rolivieri** [comment]
Thanks for your response and help. That worked; I am now getting the expected results.

**Comment by HarikaSSS** [comment]
Hi,
Object[] endKeys =  new Object[] { "1000", new Object() }
I could not use this syntax with view. because my view request is accepting startkey only of type 
Key.Complex 
Object[] startKey1 =  new Object[] { "$V-45Rtg", null, null };
Object[] endKey1 =  new Object[] { "1000", new Object(), new Object() };
db.getViewRequestBuilder("database", "test-view")
                    .newRequest(Key.Type.COMPLEX, Object.class)
                    .startKey(startKey1).endKey(endKey1).build();
the end key you suggested is an Object Array. how can i fit it in my view request?

**Comment by ricellis** [comment]
@HarikaSSS this issue is very old and refers to 1.x versions of java-cloudant.
See #400 and [this description of using `"\ufff0"`](https://github.com/cloudant/java-cloudant/issues/147#issuecomment-158930613) for the solution.
