### ISSUE TITLE
java.lang.NullPointerException in AllDocsRequestResponse.getIdsAndRevs

### ISSUE THREAD

**Issue by pavelmarek77** [cloudant/java-cloudant#297]
When calling:

		String keys[] = {"xyz","yzx"}; 
		Map<String, String> map = d.getAllDocsRequestBuilder().keys(keys).build().getResponse().getIdsAndRevs();

where keys are TWO non-existing documents, it gives:

Exception in thread "main" java.lang.NullPointerException
	at com.cloudant.client.internal.views.AllDocsRequestResponse.getIdsAndRevs(AllDocsRequestResponse.java:57)
	at com.ibm.lex.services.tags.service.impl.Cloudant.main(Cloudant.java:605)

When trying just one non-existing document, it returns empty Map (as expected).

Version 2.6.2, IBM jdk 1.8, okhhtp depenancy

**Comment by ricellis** [comment]
Thanks for reporting this. I see the problem

If a single key is used we shortcut the array and just use the query parameter `key="xyz"` which returns an empty set of rows.

If there are multiple keys we use the array form of the query parameter `keys=["xyz", "yzx"]`. When used with a `_view` this does return an empty set of rows, but when used with `_all_docs` it returns an array of results with a row for each key e.g.:
```javascript
{"total_rows":11,"offset":0,"rows":[
{"key":"xyz","error":"not_found"},
{"key":"yzx","error":"not_found"}
]}
```

The NPE results when we try to extract the revision `value` from those rows.
I'll get a fix in.
