### ISSUE TITLE
The maven jar is compiled to run on only Java 7 and up

### ISSUE THREAD

**Issue by stephenrobertson0** [cloudant/java-cloudant#30]
I therefore get the following when trying to run on Java 6:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/cloudant/client/api/CloudantClient : Unsupported major.minor version 51.0

**Comment by mariobriggs** [comment]
True. Will look to support in next release

**Comment by Samurais** [comment]
Same problem, it sucks.

> $ java -version
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

```
java.lang.UnsupportedClassVersionError: com/cloudant/client/api/CloudantClient
```

**Comment by mariobriggs** [comment]
pushed a 1.0.1 release with this taken care. Let me know how it goes on your side

**Comment by mariobriggs** [comment]
reopen if doesnt work with 1.0.1

**Comment by stephenrobertson0** [comment]
Thanks, it works.
