### ISSUE TITLE
BasicAuthInterceptor needs documentation

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#301]
Please include the following information in your ticket.
- CloudantClient (java-cloudant) version(s) that are affected by this issue: 1.6.2
- Java version (including vendor and platform): n/a
- If you're using the optional okhttp dependency: n/a
- A small code sample that demonstrates the issue: /na

The class `BasicAuthInterceptor` which is part of the public API, in Cloudant-http, requires documentation and I think it should also have a constructor  which takes a username and password parameters rather than userInfo.

**Comment by ricellis** [comment]
If we expose documentation for this we should make it clear that it is not needed under most circumstances.

**Comment by rhyshort** [comment]
That's fine, but we should expose documentation for it, since using it is a requirement when using systems like [Envoy][envoy] with [sync-android][sync]

[envoy]: https://github.com/cloudant-labs/envoy
[sync]: https://github.com/cloudant/sync-android
