### ISSUE TITLE
Provided interceptors do not appear in java doc.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#302]
Please include the following information in your ticket.
- CloudantClient (java-cloudant) version(s) that are affected by this issue. 2.6.2
- Java version (including vendor and platform). n/a
- If you're using the optional okhttp dependency. n/a
- A small code sample that demonstrates the issue. 

Both cloudant-client and cloudant-http do not include the interceptor classes which we provide to authenticate with the server. 

See http://www.javadoc.io/doc/com.cloudant/cloudant-http/2.6.2 and http://www.javadoc.io/doc/com.cloudant/cloudant-client/2.6.2

**Comment by rhyshort** [comment]
It looks like this [line](https://github.com/cloudant/java-cloudant/blob/master/cloudant-http/build.gradle#L24): `include("**/http/*")` is missing an extra `*` to correctly match sub-directory, @ricellis should the `interceptors` package be included in the java-doc?

**Comment by ricellis** [comment]
I think there is a case for exposing some of them that users are expected to interact with (e.g. the `Replay429Interceptor`). Others I'm more dubious about making API (e.g. the `CookieInterceptor`) since it is mostly handled internally.
Perhaps we should consider splitting the package.

**Comment by rhyshort** [comment]
That could work, it would certainly be the easiest way to split public interceptors from internal ones.
