### ISSUE TITLE
Anything I should be careful about performance with HTTPS connection ?

### ISSUE THREAD

**Issue by TigerAVAF6R** [cloudant/java-cloudant#303]
- CloudantClient (java-cloudant) version(s): 2.6.1
- Java version (including vendor and platform). 1.7 IBM JDK
- If you're using the optional okhttp dependency. Yes, using OKHTTP

What we noticed is that it will take longer time for first communication with Cloudant than sub-sequence requests. Is there anything we should be careful about HTTPS connection to cloudant ?

**Comment by ricellis** [comment]
There are two reasons why the first request will take longer than subsequent requests:

1. The library makes use of HTTP keep-alive ([connection pooling](http://static.javadoc.io/com.cloudant/cloudant-client/2.6.2/overview-summary.html#Connection%20pooling)). The first request needs to establish the connection with the server and perform the HTTPS handshake. Later requests will re-use the connection where possible that makes them faster, but there are circumstances that cause new connections to be established even after the first request:
    1.  When requests are made in parallel new connections may be created up to the maximum size of the connection pool.
    2.  The server will terminate idle connections after 2.5 minutes (connections may also be terminated by the client JVM after shorter idle times, but this should not apply when using okhttp (see https://github.com/cloudant/java-cloudant/issues/247).
2. The first request will also transparently obtain a session cookie by making an extra request to the `_session` endpoint before performing the request. This only happens on the first request or the first request after a cookie has expired.
