### ISSUE TITLE
Very many (if not all) database operations may throw CouchDbException, which inherits RuntimeException and is thus an unchecked exception

### ISSUE THREAD

**Issue by sevokn** [cloudant/java-cloudant#309]
I just realized that very many (if not all) Cloudant database operations may (rather unexpectedly) throw `CouchDbException`, which inherits Java's `RuntimeException` and is thus an unchecked exception.

Because of this, it's very easy to mistakenly write Cloudant API calls that do not have proper error handling since it's easy to leave exception handling out, since the exceptions thrown by the Cloudant API are not checked and thus not explicitly declared in the API method declarations.

Is this a deliberate design choice to have it like this? Perhaps to keep the API clean and easy to use? As the API is right now, it gives the impression that the actual API call never throws an exception but that any error handling logic is dependent on examining the state of the `Response` object.

Anyway, it's a bit annoying to have it hidden like that, since having proper and comprehensive error handling is quite crucial. I just stumbled upon an uncaught `CouchDbException` and realized the state of the API and now I need to wrap all my Cloudant API calls into a `try {...} catch (CouchDbException e) {...}` construct (_in addition to_ later examining the state of the `Response` object) in order to have complete error handling logic at the lowest database client level. This would have been much more obvious if the exception in the API was checked to begin with.

Please improve the Javadoc, the code examples and/or other documentation to better guide the users of the API in proper error handling. Even better, please fix the API in the next major revision.

**Comment by ricellis** [comment]
Thanks for raising this @sevokn - it was something inherited from the original lightcouch library and it is definitely something we have had in mind for the next major API change - in fact I thought we already had an issue open for it, but it appears we don't.

You are correct that the current approach is generally `Response` object for successful cases and `CouchDbException`s for errors.

The documentation is a bit sparse in this respect, we do in [at least some places](http://static.javadoc.io/com.cloudant/cloudant-client/2.6.2/com/cloudant/client/api/Database.html#update-java.lang.Object-) refer to sub-types of `CouchDbException` that may be thrown, but it should be clear throughout.

I think ultimately a move to checked exceptions from unchecked is preferable as it is more obvious to the programmer and also gives us tooling to warn/fail for missing `@throws` declarations in the javadoc.

**Comment by ricellis** [comment]
We're not going to be changing this here. Our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) follows the pattern of the [IBM Cloud SDK core](https://github.com/IBM/java-sdk-core) (which also prefers unchecked `RuntimeException`s), but we have tried to document more clearly the [error handling expectations](https://cloud.ibm.com/apidocs/cloudant?code=java#error-handling).
