### ISSUE TITLE
Timestamp JSON string to Java Timestamp Value - View.query(class)

### ISSUE THREAD

**Issue by rolivieri** [cloudant/java-cloudant#31]
Hello, I am having an issue when using the query method of the View class:

List<Image> images = myView.query(Image.class);

The above method invocation results in a JSON exception: my Image class has a timestamp instance variable, and the Gson instance used internally by the couchdb library fails to translate a string like “2015-01-23T18:25:43.511Z” to a timestamp variable.

If I could somehow configure the Gson instance used internally by the couchdb library, this exception would not occur. I understand I can configure my own Gson instance in the following way to handle timestamp strings like “2015-01-23T18:25:43.511Z” correctly:

Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss").create();

However, I am afraid I don’t know how to configure the Gson instance used internally by the couchdb library. Could you provide some guidance on how to address this issue? Thanks.

**Comment by mariobriggs** [comment]
@rolivieri The original LightCouch library did provide a public settable 'setGsonBuilder' method on CouchDbClient, but currently in java-cloudant we dont have such a mechanism. To unblock yourself right now, can you add your snippet to org.lightcouch.internal.GsonHelper.initGson() and rebuild the jar ? 
We would surely look at providing this feature without rebuild. As a reminder to ourselves this also needs to work for Indexes (currently another gson instance used here)

**Comment by mariobriggs** [comment]
@rolivieri  

I have pushed a fix to the vNext branch for this. Can you give it a try  and let me know how it goes

Here is a [gist](https://gist.github.com/mariobriggs/4a72466520023da25a22) of how to use it . 
There is also a test case at https://github.com/cloudant/java-cloudant/blob/vNext/src/test/java/com/cloudant/tests/DatabaseTest.java called customGsonDeserializerTest()

**Comment by rolivieri** [comment]
Thanks for your response. We will give this a try soon. At first glance, it looks exactly like what we would need to implement our use cases.

**Comment by rolivieri** [comment]
I just tested the code in the vNext branch and that change worked perfectly. That's exactly what we would need in the library so that it knows how to deserialize a timestamp value in the "yyyy-MM-dd'T'HH:mm:ss" format. Thanks again. Do you guys have a target date for incorporating this change into the main branch/build?

**Comment by mariobriggs** [comment]
I pushed a 1.0.1 release with this change a few minutes ago
