### ISSUE TITLE
[err] com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header required.

### ISSUE THREAD

**Issue by sandrodesantis** [cloudant/java-cloudant#313]
Please include the following information in your ticket.
- CloudantClient (java-cloudant) version(s) that are affected by this issue.
  cloudant-client-2.6.2.jar
  cloudant-http-2.6.2.jar
  commons-codec-1.6.jar
  commons-io-2.4.jar gson-2.7.jar
- Java version (including vendor and platform).
  /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk
- If you're using the optional okhttp dependency.
  NO
- A small code sample that demonstrates the issue

And I'm receiving ERROR message, looks like PUT commands don't working.

These commands are working very well:

// Note: for Cloudant Local or Apache CouchDB use:
CloudantClient client = ClientBuilder.url(new URL("http://0.0.0.0:5984")).username("admin")
.password("xxxx").disableSSLAuthentication().build();

// Show the server version
System.out.println("Server Version: " + client.serverVersion());

// Show databases
System.out.println("Dbs: " + client.getAllDbs());

// Get database
Database db1 = client.database("dash-db", true);
# 
# These commands are NOT working :

=> not working!
db1.createIndex("type", "type", null, new IndexField[]{
new IndexField("type",SortOrder.asc)});

=> not working
List objTOList = db.findByIndex("\"selector\": {\"type\": \"adoption\"}", ObjTO.class);
System.out.println("objTOList " + objTOList);

Exception =>

[err] com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header required.
[err] at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:524)
[err] at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:572)
[err] at com.cloudant.client.api.Database.createIndex(Database.java:305)
[err] at com.cloudant.client.api.Database.createIndex(Database.java:288)

Any idea ?, thanks !

Sandro

**Comment by ricellis** [comment]
@sandrodesantis what version of Cloudant Local are you using?

**Comment by ricellis** [comment]
The `createIndex` and `findByIndex` methods utilize the [Cloudant query](https://docs.cloudant.com/cloudant_query.html) endpoints `_index` and `_find`. Those endpoints are not available in CouchDB 1.6 and it returns the `400 Bad Request Referer header required` error.
The requests will work if you use Cloudant Local or the Cloudant service.
