### ISSUE TITLE
Support new view parameters

### ISSUE THREAD

**Issue by rhyshort** [cloudant/java-cloudant#322]
CouchDB 2.1.0 will include new view options to replace the existing `stale` parameter. These new parameters are shown in the table below with their mappings to the old API.

|# |	New API |      Old API   | Observed Behaviour (q=8,n=3)|
|--|----------|------------|--------------------------------|
|1|stable=true&update=true|Didn't exist|Blocks; Only 8 ushard indexers started|
|2|stable=true&update=false|stale=ok|Non-blocking; no indexers started; Matches previous API
|3|stable=true&update=lazy|stale=update_after|Non-blocking; 24 indexers started; Matches previous API|
|4|stable=false&update=true|stale not defined|Blocks; 24 indexers started; Matches previous API
|5|stable=false&update=false|Didn't exist|Non-blocking; no indexers started
|6|stable=false&update=lazy|Didn't exist|Non-blocking; 8 indexers started, all same node
------------

See [COUCHDB-3227](https://issues.apache.org/jira/browse/COUCHDB-3227)

**Comment by sevokn** [comment]
Is implementing this on the roadmap?

If yes, when?

If not, is there any workaround way of achieving the functionality provided by the new Cloudant API (`stable` and `update` URL parameters) through the java-cloudant API?

Adding support for this should not be too hard, it's a shame that all the existing Cloudant API is not available to Java developers...

**Comment by emlaver** [comment]
@sevokn We intend to address this in the next major version.
You can call `executeRequest` to use the additional view parameters.  See the [java-cloudant documentation for more details.](https://static.javadoc.io/com.cloudant/cloudant-client/2.11.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-)
e.g.
```
CloudantClient client = ClientBuilder.account("examples").build();
Database db = client.database("animaldb", false);
HttpConnection allDocsGet = Http.GET(new URL(db.getDBUri() + "/_all_docs?stable=true&update=true"));
System.out.println(client.executeRequest(allDocsGet).responseAsString());
```

>{"total_rows":11,"offset":0,"rows":[
{"id":"_design/views101","key":"_design/views101","value":{"rev":"1-a918dd4f11704143b535f0ab3af4bf75"}},
...
{"id":"zebra","key":"zebra","value":{"rev":"3-750dac460a6cc41e6999f8943b8e603e"}}
]}

**Comment by tomblench** [comment]
Closing as PR merged
