### ISSUE TITLE
save image file or audio file as attachment to cloudant

### ISSUE THREAD

**Issue by zeevmindali** [cloudant/java-cloudant#329]
Dear all,

i using the latest client to cloudant.
i want to add attachment (can be image file of jpg,png or audio file 3gp).
is there an example how to use it with android studio or java?

zeev

**Comment by rhyshort** [comment]
The [attachments documentation](http://static.javadoc.io/com.cloudant/cloudant-client/2.7.0/overview-summary.html#Attachments) has some examples, but the gist is use the `Database#saveAttachment` method to upload the attachment separately to the document or save the attachment inline with the document like:

```java
Attachment attachment = new Attachment();
attachment.setData(Base64.encodeBase64String("attachment test string".getBytes()));
attachment.setContentType("text/plain");
Foo foo = new Foo(); // Foo extends Document
foo.addAttachment("attachment.txt", attachment);
db.save(foo);
```

Based on the file types you using, it would probably be best to upload the attachment separately to the document.

**Comment by zeevmindali** [comment]
if upload the image and then save the database, the image will be at the database?

**Comment by zeevmindali** [comment]
tried to save the attchment as inputstream.
got duplicate entry on the cloud net, one is data second is attachment, but not with the picture.

{
  "_id": "2fc4491105de4e929273ddfa878c49c4",
  "_rev": "1-a9f86257d3ca10822fd29bdf42ca35e1",
  "_attachments": {
    "thumb": {
      "content_type": "image/jpg",
      "revpos": 1,
      "digest": "md5-pjQlgP+nCrOrs9l5+vgE3A==",
      "length": 1033,
      "stub": true
    }
  }
}

**Comment by zeevmindali** [comment]
o.k. , i got to upload the image , using inputStream.
how i can get an url address to my attachment?

**Comment by rhyshort** [comment]
The byte stream passed to the `saveAttachment` method is read by the server and the attachment is stored in the Cloudant database if the request completes successfully. There is no `save` for the database.

The three argument version of `saveAttachment` creates a _new_ document which only contains the attachments. The 5 argument version will create a new _revision_ of a n existing document which contains all the data of the previous revision with the attachment added. 

When receiving the document from the server the attachment content is *not* included by default. To access the attachment for the document you provided you would go to `https://<accountName>.cloudant.com/<dbName>/2fc4491105de4e929273ddfa878c49c4/thumb`

**Comment by rhyshort** [comment]
For standalone access to the attachment using the client:

```java
try {
   HttpConnection conn = Http.GET(new URL(db.getDBUri() + "/2fc4491105de4e929273ddfa878c49c4" + "/thumb"));
   InputStream in = client.executeRequest(conn).responseAsInputStream();
} catch (CouchException e) {
   // handle exception
} catch (MalformedURLException e){
   // handle exception
}
```

**Comment by zeevmindali** [comment]
thank you a lot, finally, working like a charm, with the fastest responses that i ever had.
this is why each day i say "IBM is the right choice"

Keep up the good work, and thanks a lot.

**Comment by rhyshort** [comment]
Great glad you've got it working.
