### ISSUE TITLE
Cloudant object pooling?

### ISSUE THREAD

**Issue by stephenzr** [cloudant/java-cloudant#34]
We started seeing memory run ups after putting the library under low load over a number of hours. The datasets are not trivial, maybe 50k docs with 20 fields. 

But the question is really about using the cloudant client efficiently.
Is it best to use a single singleton instances across a tomcat app?
Or should we create a pool of them?
Or just create as needed?
Always call shutdown (i saw apache http client is used underneath which recommends cleaning up.)
Thanks.

**Comment by mariobriggs** [comment]
@stephenzr in my usage so far which i wouldn't categorize as very very heavy, i have always gone with a single singleton instance across the app. So i would suggest to always start with that. Further, i keep a singleton instance of each of the DB's in use too (u dont want to make http roundtrips just to get the DB uri).
Yes we use apache http client underneath which handles multiple threads on single instance. You can set the (maxConnections)[https://github.com/cloudant/java-cloudant#advanced-configuration] to be used by the apache http client.

**Comment by stephenzr** [comment]
Hey Mario, thanks for the info.  That sounds a like a decent approach to try.  We'll give it a shot.  Thanks for sharing.
