### ISSUE TITLE
Upgrade version of httpclient

### ISSUE THREAD

**Issue by cavanaugh-ibm** [cloudant/java-cloudant#35]
There is a bug in < http client 4.3.6 that allows a read to block forever even when socket timeout is set.

**Comment by mariobriggs** [comment]
thanks. Was on todo list, will spin a run of the test suite with the latest stable Apache httpClient

**Comment by ricellis** [comment]
Upgraded Apache HttpClient to 4.3.6 in release [1.2.2](https://github.com/cloudant/java-cloudant/releases/tag/1.2.2)
