### ISSUE TITLE
docs: queryView()

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#36]
`com.cloudant.client.api.View.queryView(Class k, Class v, Class t)`  can use some more docs. In particular, `t` is the type of the doc, `k` the type of the key, and `v` of the value.  This is handy when querying something that has a complex key.

**Comment by mariobriggs** [comment]
@srl295 sure. Do you want to try a Pull Request ?

**Comment by srl295** [comment]
@mariobriggs sure! Also: I think 
`com.cloudant.client.api.model.ViewResult.Rows` should just be named `Row` because it is returned like this:  ` List<Rows> getRow()`.  I see lightcouch calls it Rows though.

**Comment by emlaver** [comment]
@srl295 I've made changes to the javadoc for `com.cloudant.client.api.View.queryView(Class k, Class v, Class t)`.  If you could review and leave some comments about the changes, that would be appreciated.  Thanks!

**Comment by emlaver** [comment]
Updated Javadoc for `queryView`:
https://github.com/cloudant/java-cloudant/blob/master/src/main/java/com/cloudant/client/api/View.java#L75-L126

**Comment by emlaver** [comment]
@srl295 Renaming `com.cloudant.client.api.model.ViewResult.Rows` to `Row` could be a breaking change in version 1.x.   We’re working on a replacement View API for version 2.x and it will include this change and many other fixes.

**Comment by mikerhodes** [comment]
Closing for now; I think we've address the issues; let me know if we've not.

**Comment by srl295** [comment]
+1
