### ISSUE TITLE
Cloudant database bulk operation does not overwrite document for List based members

### ISSUE THREAD

**Issue by mandeepchana** [cloudant/java-cloudant#362]
Please include the following information in your ticket.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.

  Tried both 2.7.0 and 2.9.0 here are the gradle dependencies I used

  compile group: 'com.cloudant', name: 'cloudant-client', version: '2.9.0'
  compile group: 'com.cloudant', name: 'cloudant-http', version: '2.9.0'

- Java version (including vendor and platform).

java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp21-20161117_02(SR3 FP21))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20161114_325917 (JIT enabled, AOT enabled)
J9VM - R28_20161114_0146_B325917
JIT  - tr.r14.java.green_20161111_127476
GC   - R28_20161114_0146_B325917_CMPRSS
J9CL - 20161114_325917)
JCL - 20161116_01 based on Oracle jdk8u111-b14

on Redhat 6.9

- A small code sample that demonstrates the issue.

I have the following code structure:

**Entity.java:**

public class Entity extends CloudantObject {
      
       @ApiModelProperty(value = "entityItems", required=true)
       List<EntityItem> entityItems;
      
       @JsonCreator
       public Entity(@JsonProperty("name") String name, 
                           @JsonProperty("entityItems") List<EntityItem> entityItems) {
		super();
		this.name = name;
		this.entityItems = entityItems;
		this.set_id(name);
	}
}

**EntityItem.java:**

public class EntityItem {
        
        @NotNull
	    @ApiModelProperty(value = "synonyms", required = true)
	    private String[] synonyms;
 
        @JsonCreator
	    public EntityItem(@JsonProperty("value") String value,
                               @JsonProperty("synonyms") String[] synonyms) {
		     this.synonyms = synonyms;
		     this.value = value;
	        }
        }

What I am seeing is that the com.cloudant.client.api.Database.bulk call does not reflect the values in the synonyms class member, during an update. Cloudant is retaining the old synonyms so if I start with the following cloudant entry:

[{      "name": "Level",
        "entityItems": [{
            "value": "latest",
            "synonyms": ["newest","new","recent","current"]
        }]  }]

The synonyms part cannot be overwritten using the bulk method

**Comment by ricellis** [comment]
Can you give us a snippet of the java-cloudant call you are using? Is it `db.bulk()` with a `List<Entity>`?
Were all the repsonses returned in the `List<Response>` OK or did the server complain?
Have you attempted to update a single document using `db.update()`, does that work?

**Comment by mandeepchana** [comment]
Sure, so the call we are making into bulk is wrapped in the following method:

public static <T> List<Response> bulk(java.lang.Class<T> classType, List<T> cloudantObjects) {
		Database db = getDatabase(classType);
		return db.bulk(cloudantObjects);
} ... part of DatabaseUtil

So effectively we have a database for a particular class type.  The call into that method looks like

public boolean bulk(Entity[] entities) {
		LOG.info("[ConversationDataStore.createEntities] START");
		DatabaseUtil.bulk(Entity.class, Arrays.asList(entities));
		LOG.info("[ConversationDataStore.createEntities] END");
		return true;
}

I'll need to check the response. But that is probably an oversight on our part and we should check it.
The individual db.update works fine its just the bulk update.

**Comment by mandeepchana** [comment]
Hi so added the output of Response in the following way:

public boolean bulk(Entity[] entities) {
		LOG.info("[ConversationDataStore.createEntities] START");
		List<Response> responses = DatabaseUtil.bulk(Entity.class, Arrays.asList(entities));
		
		for (Response response: responses) {
			LOG.info("Got bulk entity responseError: {}",response.getError());
			LOG.info("Got bulk entity responseReason: {}",response.getReason());
			LOG.info("Got bulk entity responseId: {}",response.getId());
		}
		LOG.info("[ConversationDataStore.createEntities] END");
		return true;
	}

and got as output 

INFO  [2017-07-27 16:26:32,638] com.ibm.cloud.wms.conversation.data.ConversationDataStore: [ConversationDataStore.createEntities] START
INFO  [2017-07-27 16:26:32,904] com.ibm.cloud.wms.conversation.data.ConversationDataStore: Got bulk entity responseError: conflict
INFO  [2017-07-27 16:26:32,905] com.ibm.cloud.wms.conversation.data.ConversationDataStore: Got bulk entity responseReason: Created
INFO  [2017-07-27 16:26:32,905] com.ibm.cloud.wms.conversation.data.ConversationDataStore: Got bulk entity responseId: UsageRanking

so i guess the bulk thinks there is a conflict, but wondering if this should act as a PUT statement and hence just overwrite rather then a conflict

**Comment by ricellis** [comment]
>act as a PUT statement and hence just overwrite rather then a conflict

A `PUT` in CouchDB/Cloudant doesn’t "overwrite", it generates a new revision in the tree branching from the `_rev` supplied. If you don’t supply a `_rev` it will try to create a new doc (i.e. a `1-…` generation revision). So for example if you don’t supply any `_rev` information in the objects in the `List` you are passing to the `bulk()` method the server will try to create new `1-…` revs for all those documents, which if they are existing documents would be a conflict.

Basically if you’re getting a conflict it is because the revision of the document that you are trying to update is not the latest (i.e. has already been updated). This could be either because you are supplying the wrong or outdated `_rev` information or the document has been simultaneously updated from another source.

A few things to check:
* Are you sure that your serialization is including a `_rev` ID (or the correct `_rev` ID)?
* Are you updating the `_rev` IDs in your Java objects after create or previous updates? (Consider this [documentation point](http://static.javadoc.io/com.cloudant/cloudant-client/2.9.0/overview-summary.html#Document%20revisions))
* Are there other updates happening at the same time that could cause a conflict?

**Comment by mandeepchana** [comment]
Thanks, that was indeed the problem. I had to get hold of the _rev values based on the _id. Once I populated that back into the individual object it works. Thanks again.
