### ISSUE TITLE
Cookie interceptors should check for expiry

### ISSUE THREAD

**Issue by tomblench** [cloudant/java-cloudant#363]
We can optimise the cookie interceptors by checking if the existing cookie has expired in the request interceptor. This can be done by storing the cookie expiry date and checking it for each request, and we can avoid having to replay a request we know will fail.

**Comment by ricellis** [comment]
The default `CookieManager` uses the default `CookieStore` and the doc for [`getCookies()`](https://docs.oracle.com/javase/7/docs/api/java/net/CookieStore.html#getCookies()) and [`get(URI uri)`](https://docs.oracle.com/javase/7/docs/api/java/net/CookieStore.html#get(java.net.URI)) both state that they will return only non-expired cookies. As such I don't think we need add any code for this optimization.

I think we should tests though to validate it behaves as expected and ensure there are no platform inconsistencies.

**Comment by ricellis** [comment]
This appears to work as described/expected. I'll get a PR open for my test.
