### ISSUE TITLE
com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header

### ISSUE THREAD

**Issue by santooudnur** [cloudant/java-cloudant#378]
I have added document in Couch DB . Example document
{
"_id": "2505c3877b3b452789e36a0bdb6b87c4",
"_rev": "1-51ed68335739607895e4b2da802c8760",
"transaction": {
"transaction_id": "-11111111",
"is_json_read": true,
"is_json_valid": false,
"has_bmsiw_document": false,
"bmsiw": {
"has_bmsiw_data": false,
"fetched_bmsiw_add_meta_data": false
},
"is_json_tansformed": false,
"is_nlu_processed": false,
"is_nlu_bmsiw_merged": false
}
}
Now I have transaction_id with me, based on the same I need to fetch the document and then update the same document in db.

I am trying to use method findByIndex(selector,ClassT) but getting error
com.cloudant.client.org.lightcouch.CouchDbException: 400 Bad Request: bad_request: Referer header required.
following in selector JSON
{
"selector": {
"transaction": {
"$eq": "-11111111"
}
},
"fields": "[_id, _rev, transaction]"
}

Please let me know the solution for the same

- CloudantClient (java-cloudant) version(s) that are affected by this issue. -2.7.0
- Java version (including vendor and platform). -
- If you're using the optional okhttp dependency.
- A small code sample that demonstrates the issue.

**Comment by smithsz** [comment]
Hey @santooudnur,
Your selector looks incorrect to me. I think you're after something like this:
```js
{
  "selector": {
    "transaction.transaction_id": {
      "$eq": "-11111111"
    }
  },
  "fields": ["_id", "_rev", "transaction"]
}
```
If this doesn't solve the problem then please provide a code snippet showing how you're creating the selector class? Thanks.

**Comment by santooudnur** [comment]
@smithsz Issue is solved renamed transaction, along with changes you mentioned.transaction_id to transaction.transactionId it worked. seems _ is not supported in key names as system keys like id ,rev starts with -. Thank you for your support.
