### ISSUE TITLE
Is it possible to parse keys that are complex objects in a view

### ISSUE THREAD

**Issue by AparnaPillai46** [cloudant/java-cloudant#386]
I want to parse my key into objects from the view. My key is something like this ... Is this possible ?

"key":{
"pId":"xxxx",
"pType":"yyy",
"pName":"xxx",
"spT":"qqqq",
"ind":"Y",
"order":1,
"templ":"aaaaa",
"p":[ "aaaaa"]
}

```
ViewResponse<Object, Obj> s = db.getViewRequestBuilder("xx", "yy").newRequest(Key.Type.<XX>, Policy.class)
					.limit(10)
					.includeDocs(true)
					.build()
					.getResponse();
List<Row<Object, Obj>> rows = s.getRows();
			for (Row eachRow : rows){
			 eachRow.getKey();//this comes as NULL 
			
}
```
s ->rows->elementData->row has the JSON structure with id,key,value and doc.
There is a "getDocumentAsType" . Is there something similar to getKeyAsType ? 

Is it possible to get ViewResponse having object as Key or is there a way to return the JSON string associated with the key ?

**Comment by emlaver** [comment]
Hi @AparnaPillai46, our `java-cloudant` view API does not support keys of JSON object type. Keys emitted from a view are sorted and while [CouchDB view collation](http://docs.couchdb.org/en/latest/ddocs/views/collation.html#collation-specification) is well defined, JSON objects are generally un-ordered in other systems. We can’t guarantee the ordering of object keys when we serialize JSON object keys, which could lead to inconsistent view results so we recommend using arrays.

See also this [stackoverflow answer](https://stackoverflow.com/a/7605515/5878650) and this [detailed response on grokbase.com](http://grokbase.com/t/couchdb/user/118h3gb1dm/map-reduca-with-object-as-key#20110818fwvqn6vf4vw3h65y2cch43yegm).

**Comment by AparnaPillai46** [comment]
Well.. I need the Key as Object as it makes sense to keep it as an Object. I'll try calling it as a REST call and parse keys and docs...

**Comment by emlaver** [comment]
@AparnaPillai46 you can make HTTP requests using the [CloudantClient#executeRequest method](https://github.com/cloudant/java-cloudant/blob/dde30d749c19eb90e2b1b7f25b26d58a934d8613/cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java#L334).

**Comment by emlaver** [comment]
Closing as stale.
