### ISSUE TITLE
Support bookmarks in the Query api

### ISSUE THREAD

**Issue by willholley** [cloudant/java-cloudant#387]
Cloudant Query now supports bookmarks across all index types - previously this was only supported/required for text indexes. We should ensure that bookmarks, where present, are available in the query result objects and support passing a bookmark as part of the query object.

Ideally this would be extended so that we expose a consistent pagination approach for all index APIs and the bookmark management would be hidden from the user e.g. an an iterable. The Query behaviour is largely modelled on the existing support in Lucene/Search indexes so perhaps there's some possible code reuse there.

**Comment by ricellis** [comment]
See also #159 for consistent paging.
