### ISSUE TITLE
startKey/endKey with complex keys

### ISSUE THREAD

**Issue by srl295** [cloudant/java-cloudant#39]
I think there's a bug with the startKey and endKey functions as well as key()

Even in the `ViewsTest` there is this snippet in `byComplexKey()`
```
	public void byComplexKey() {
		int[] complexKey = new int[] { 2011, 10, 15 };
		List<Foo> foos = db.view("example/by_date")
				.key(complexKey)
//				.key(2011, 10, 15) 
```

I think the problem is that one `(Object...)` function is calling another `(Object...)` function.  I can't remember how to fix this yet, but want to capture.

I had to do similar code to the above workaround in my own project.

**Comment by mariobriggs** [comment]
a test case with expected results and received results would be good. For instance we had usage issues like #29

**Comment by srl295** [comment]
@mariobriggs thanks. I'm trying to make a test case.

**Comment by ricellis** [comment]
The `ViewsTest.byComplexKey()` works with `view.key(2011,10,15)` since release 1.1.2.
