### ISSUE TITLE
db.changes is not returning all changes

### ISSUE THREAD

**Issue by devnieL** [cloudant/java-cloudant#40]
Hi,

I found a problem with changes stream, even in the rest api. It's not returning the same results than the cloudant dashboard. I have tried the style("all_docs") option but it's returning the same.

Also, I have found that sometimes the result is different while calling the changes endpoint through the rest api : https://xxx.cloudant.com/dashboard.html#/database/yyy/_changes?

Thanks

**Comment by mariobriggs** [comment]
@devnieL for the former maybe u should consider reaching cloudant support ? (BTW i am sure you know this, but just in case..... the changes log is not guaranteed to be in chronological order)

For the 2nd, if you provide a example like done in #29 then i can look into

**Comment by ricellis** [comment]
@devnieL did you follow this up with Cloudant support? If not could you explain how the result was different (e.g. different ordering or missing items)

**Comment by ricellis** [comment]
As per the [Cloudant documentation for _changes](http://docs.cloudant.com/database.html#get-changes) one replica from each shard is asked to provide a list of changes. As a result it is possible that different results could be returned from requests depending on which replica is asked and the state of the replicas.

@mikerhodes adds:
> The only guarantee offered by the changes feed is that if you pass in a sequence number, you will see all changes that have happened since that sequence number (up to your limit).
>Note that this doesn't preclude:
>* Ignoring the sequence number entirely and responding with _all_ changes.
>* Repeating changes, either within or between changes batches.
>* Reordering changes.
>* And many other things.

@devnieL I am going to close this issue as a likely being one of these scenarios, but feel free to re-open if you are able to demonstrate that the changes are not meeting that guarantee.
