### ISSUE TITLE
Using endKey for Key.Type.COMPLEX type

### ISSUE THREAD

**Issue by tejact** [cloudant/java-cloudant#400]
I have a view and queried with this REST request

```
https://<cloudant-view-url>?start_key=[xyz]&end_key=[xyz,{}]
```
Trying to implement same request with the SDK. Here is the one I have used
```
 Key.ComplexKey startKey = Key.complex("xyz");
 Key.ComplexKey endKey = Key.complex("xyz","{}");
 ViewResponse<Key.ComplexKey,String> viewResponse =   viewRequestBuilder
                                                            .newRequest(Key.Type.COMPLEX, String.class)
                                                            .startKey(startKey)
                                                            .endKey(endKey)
                                                            .build()
                                                            .getResponse();
```
This query is not returning any rows. I found similar issue #29, but can't pass and empty object `new Object()` here because the `Key.ComplexKey` can have  string, number or  booleans

Please suggest a way to use `{}` as part of complex key.

**Comment by ricellis** [comment]
The solution is to use the string `"\ufff0"` as [described here](https://github.com/cloudant/java-cloudant/issues/147#issuecomment-158930613).

**Comment by tomblench** [comment]
closing, see #147
