### ISSUE TITLE
Can I Use This library in JavaFx Application to develope Offline first desktop application ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/java-cloudant#403]
Please include the following information in your ticket.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
- Java version (including vendor and platform).
- If you're using the optional okhttp dependency.
- A small code sample that demonstrates the issue.

**Comment by tomblench** [comment]
You have two options:
- Use [sync-android](https://github.com/cloudant/sync-android) which can be used on any J2SE platform, which should include a JavaFx application. Despite the name, it will run and is tested on the J2SE platform.
- Use this library (java-cloudant), and implement the CRUD logic to keep your application's state synchronised with the remote database.

**Comment by ZaheerUdDeen** [comment]
@tomblench Thank you!
