### ISSUE TITLE
How to receive document from Cloudand as JSON ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant/java-cloudant#404]
Please include the following information in your ticket.

![cldnt](https://user-images.githubusercontent.com/11150958/33875278-946c089a-df43-11e7-9b45-a2ed43228f39.PNG)

-Instead of receiving Cloudant document like that(In attached Picture ) how can I receive the document in pure JSON form.
-In case of the same procedure, how can I receive a nested JSON or JSON containing multiple arrays?

**Comment by tomblench** [comment]
There is no native JSON type in Java so you have decide how you want to deserialise the data. Below are a few options:

Get response as `InputStream` for further processing with your favourite JSON deserialiser etc:
```java
InputStream is = db.find(documentName);
// now read and process the InputStream
```
or
Get response as `Map`
```java 
Map<String, Object> m = db.find(Map.class, documentName);
// above will cause an unchecked assignment warning but keys in the map are guaranteed to be Strings
```
You can deserialise arbitrarily complex and nested structures. Our code uses GSON to do this. For more information I would recommend reading the [GSON guide](https://github.com/google/gson/blob/master/UserGuide.md).

**Comment by tomblench** [comment]
closing, no further action
