### ISSUE TITLE
AuthCookie may not be null 

### ISSUE THREAD

**Issue by challenjour** [cloudant/java-cloudant#41]
I am currently getting a java.lang.IllegalArgumentException: AuthCookie may not be null.

Here is my code

public class Cloudant {
	public static void main (String[] args){
		
	String password = System.getProperty("gffgasdas");
	CloudantClient client = new CloudantClient("test1234.cloudant.com",password);

	System.out.println("Connected to Cloudant");
	System.out.println("Server Version: " + client.serverVersion());
	
	List<String> databases = client.getAllDbs();
	System.out.println("All my databases : ");
	for ( String db : databases ) {
	    System.out.println(db);

**Comment by mariobriggs** [comment]
the 2 string argument constructor of CloudClient is for when u want to login reusing a existing AuthCookie, which doesn't seem to be your case here. Therefore you want to change your 2nd line of code to

~~~
CloudantClient client = new CloudantClient("test1234","test1234",password);
~~~

the first argument is the account to connect to cloudant DBaas (u dont need to specify the cloudant.com), the 2nd is the accountname OR apikey to connect as and the 3rd is the password for the accountname or apikey specified in the 2nd argument.

**Comment by challenjour** [comment]
Thanks for the reply I have changed what you have suggested but am now getting the following:
Exception in thread "main" java.lang.IllegalArgumentException: password may not be null.
	at org.lightcouch.internal.CouchDbUtil.assertNotEmpty(Unknown Source)
	at com.cloudant.client.api.CloudantClient.<init>(Unknown Source)
	at sample.Cloudant.main(Cloudant.java:11)

Cloudant:java 11 is the CloudantClient client = new CloudClient line

**Comment by challenjour** [comment]
Thanks for your help!
