### ISSUE TITLE
during creating docuemnt in cloudant db db.save() call is returning HTTP status code 412 

### ISSUE THREAD

**Issue by pravingurav** [cloudant/java-cloudant#413]
Please include the following information in your ticket.

- CloudantClient (java-cloudant) version(s) that are affected by this issue. : 2.9.0
- Java version (including vendor and platform). : java 8
- If you're using the optional okhttp dependency. : No
- A small code sample that demonstrates the issue.
public <T extends Document> CommonResponseDTO createOrUpdate(T jsonObject, String dbName) {
LOGGER.debug("start the createOrUpdate()");
CommonResponseDTO commonResponseDTO = new CommonResponseDTO();
Response response = null;
Database db;
String docId;
try {
db = cloudantClient.database(dbName, false);
docId = jsonObject.getId();
if (StringUtils.isEmpty(docId)) {
/* create json */
response = db.save(jsonObject);
} else {
/* check if database already exists record */
if (!db.contains(docId)) {
/* create json */
response = db.save(jsonObject);
} else {
/* update json */
response = db.update(jsonObject);
}
 
}
db.ensureFullCommit();
 
if (response != null && (response.getStatusCode() == HttpStatus.OK.value()
|| response.getStatusCode() == HttpStatus.CREATED.value())) {
CommonResponseHandling.successResponseWithData(commonResponseDTO, response.getId(), null,
DOC_CREATE_SUCCESS_MSG);
} else {
CommonResponseHandling.failCreateOrUpdate(commonResponseDTO);
}
 
} catch (RuntimeException e) {
throw new RestCommonException(e);
}
 
LOGGER.debug("end the createOrUpdate()");
return commonResponseDTO;
}

**Comment by emlaver** [comment]
Hi @pravingurav, I'll try your code locally.  At line `response = db.update(jsonObject)` can you verify through debugging that the `jsonObject` has the required `_id` and `_rev` fields for updating?

**Comment by pravingurav** [comment]
Json object contains _id and _rev...Problem is not with the update...it is with the create db.save call (I am not passing _id for create call... cloudant it self is generating _id if I don't send)...sometimes this code behaves abnormally and send 412 error saying database already created though I am not trying to create  database...I am facing this issue less frequently though...but I am worried for long run...

**Comment by emlaver** [comment]
The only call that can return the 412 exception is [client.createDB("db_name")](https://github.com/cloudant/java-cloudant/blob/7f8af92337e34a6ac59042cb8b3f7887af62122d/cloudant-client/src/main/java/com/cloudant/client/api/CloudantClient.java#L235-L248).   Is it possible that this method is called in another part of your codebase?

**Comment by pravingurav** [comment]
Hi,
No we never call client.createDB() through API. Please check below logs it is pointing to com.cloudant.client.api.Database.save(Database.java.710)

stacktrace:
Caused by: com.cloudant.client.org.lightcouch.PreconditionFailedException: 412 Precondition Failed at https://dig-cdntuatlb.corp:443/auth. Error: file_exists. Reason: The database could not be created, the file already exists..
	at com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:519)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:579)
	at com.cloudant.client.org.lightcouch.CouchDbClient.executeToResponse(CouchDbClient.java:292)
	at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:425)
	at com.cloudant.client.org.lightcouch.CouchDbClient.put(CouchDbClient.java:394)
	at com.cloudant.client.org.lightcouch.CouchDatabaseBase.save(CouchDatabaseBase.java:196)
	at com.cloudant.client.api.Database.save(Database.java:710)
	at com.ibm.cloudant.common.dao.impl.CommonCloudantDaoImpl.createOrUpdate(CommonCloudantDaoImpl.java:219)

**Comment by smithsz** [comment]
This doesn't look like a Cloudant URL. Are you proxying your requests? If so, how is the proxy configured?

You should only see the `Error: file_exists. Reason: The database could not be created` response when attempting to create a database that already exists. In your log output above, the `PUT https://dig-cdntuatlb.corp:443/auth` request is attempting to create a database called `auth`.

This suggests you're mangling the URLs from within the proxying layer and therefore mistakenly hitting a database endpoint, not a document endpoint. Can you confirm?

Thanks.

**Comment by pravingurav** [comment]
I am using cloudant local installation
**accessing cloudant information from propery file:**
cloudant.username=admin
cloudant.password=XAwBQWu1UKgidbUTdjfGNV==
cloudant.url=https://dig-cdntuatlb.corp

**Code for creating cloudantClient bean:**
private String basicAuth() {
  StringBuilder builder = new StringBuilder();
  builder.append(getUserName());
  builder.append(":");
  builder.append(getPassword());
  return builder.toString();
 }
 @Bean
 public CloudantClient cloudantClient() {
  CloudantClient cloudantClient = null;
  try {
   cloudantClient = ClientBuilder.url(new URL(getUrl())).gsonBuilder(new GsonBuilder())
     .interceptors(new BasicAuthInterceptor(basicAuth())).maxConnections(100000).build();
  } catch (MalformedURLException e) {
   throw new RestCommonException(e);
  }
  return cloudantClient;
 }

**using this Cloudant client bean for fetching database using below code:**
db = cloudantClient.database(dbName, false);

I am not able to re-produce this issue...Even I am surprised to see this URL https://dig-cdntuatlb.corp:443/auth during creating document. As i explain you earlier it is causing when i dont send id during create call(Cloudant is creating its own id if i dont send).

**Comment by smithsz** [comment]
Is `auth` the name of the database? What is the name of the document you wish to access?

Can you access the document successfully via cURL in the terminal?
```sh
curl -u <username> https://dig-cdntuatlb.corp:443/auth/<docid>
```

I can't see anything in your code snippet that would be causing this error. Lets try to simplify the client construction before proceeding. Please try building the client as follows:
```java
ClientBuilder.url(new URL("https://dig-cdntuatlb.corp"))
             .username(getUserName())
             .password(getPassword())
             .build();
```
_(See [Getting Started](https://github.com/cloudant/java-cloudant#getting-started) documentation)_

**Comment by tomblench** [comment]
Closing old ticket, please re-open if you are still experiencing issues.
