### ISSUE TITLE
visibility problem

### ISSUE THREAD

**Issue by vito490** [cloudant/java-cloudant#414]
Please include the following information in your ticket.

- my CloudantClient is the 0.0.1
- i'm using java 8
- not using okhttp dependency.
 public InputStream queryForStream(String query) {
        key(query);
        URI uri = databaseHelper.build();
        HttpConnection get = Http.GET(uri);
        get.requestProperties.put("Accept", "application/json");
        return client.couchDbClient.executeToInputStream(get);
    } 
in this method i've just shown, the problem is that tha visibility of the value "couchDbClient" doesn't let me use it in my class that is in another package. Do you know why this appends?

**Comment by tomblench** [comment]
Closing ticket; user is on an old, unsupported version.
