### ISSUE TITLE
contentType shall be allowed an empty string

### ISSUE THREAD

**Issue by Kenzku** [cloudant/java-cloudant#417]
Please include the following information in your ticket.

The `db.saveAttachment` shall allow empty contentType, as the contentType would be unknown via octet stream uploading, also, the couch db web interface attachment upload allows empty contentType.

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
2.11.0

- Java version (including vendor and platform).
java version "1.8.0_144"
Java(TM) 2 Runtime Environment, Standard Edition (IBM build 1.8.0_144-b01 31_Jul_2017_10_49 Mac OS X x64(SR4 FP10))
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
IBM Java ORB build orb80-20170718.00
XML build XL TXE Java 1.0.58
XML build IBM JAXP 1.6.1
XML build XML4J 4.5.29

- If you're using the optional okhttp dependency.
nope

- A small code sample that demonstrates the issue.
```Java
  Database db = client.database("ken_test_attachment", false);
  # you can get attachment input stream from a file or MediaType.APPLICATION_OCTET_STREAM while upload
  # set contentType to an empty string 
  db.saveAttachment(attachmentInputStream, "AjaxProxy.war", "");
```

Got error:

```log
ContentType may not be empty.
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.cloudant.client.org.lightcouch.internal.CouchDbUtil.assertNotEmpty:60'
java.lang.IllegalArgumentException: ContentType may not be empty.
```

If upload directly to CouchDb, contentType is empty:
<img width="828" alt="screen shot 2018-02-08 at 13 32 00" src="https://user-images.githubusercontent.com/1387249/35975575-11bffc48-0cd5-11e8-8293-f29958a02e56.png">

**Comment by tomblench** [comment]
If your content type is `application/octet-stream`, I would recommend explicitly setting the content type to that value when calling `db.saveAttachment`.

Note that the [Cloudant documentation](https://console.bluemix.net/docs/services/Cloudant/api/attachments.html#create-update) states that "The attachment's content type must be specified using the Content-Type header". The [CouchDB documentation](http://docs.couchdb.org/en/stable/api/document/attachments.html#put--db-docid-attname) also states "Content-Type – Attachment MIME type. Required".

As you have observed, you can use `curl` or other tools to send an empty string for the content type, and the server will automatically set the content type to `application/octet-stream`.

So the current behaviour deviates from the documented behaviour. I think we're correct in enforcing the documented behaviour because this should be the "source of truth". It's quite possible that this behaviour will change in newer versions.

**Comment by Kenzku** [comment]
@tomblench but if you upload a binary via the UI, the content_type is set to empty by default

**Comment by ricellis** [comment]
The CouchDB/Cloudant HTTP API documentation is clear that the `Content-Type` header is required and that is the behaviour we enforce in java-cloudant, even though the method javadoc could be more clear that the parameter is required.

>but if you upload a binary via the actual product's UI, the content_type is set to empty by default

Not quite, in practice the behaviour of the CouchDB dashboard varies by version. Considering an example where I upload two different attachment types with no `Content-Type` header using the dashboard or curl here is the outcome of what is set in the document `content_type` field for the attachment:

Upload via | attachment | CouchDB 1.x `content_type` | CouchDB 2.x `content_type`
--- | --- | --- | ---
Dashboard | mypic.png | `"image/png"` | `"image/png"`
Dashboard | profiling.nps | `"application/octet-stream"` | `""`
curl | mypic.png | `"application/octet-stream"` | `"application/octet-stream"`
curl | profiling.nps | `"application/octet-stream"` | `"application/octet-stream"`

So you can see that if a `Content-Type` header is *omitted* from a request the server assumes `application/octet-stream`. This is in line with the [HTTP spec](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) which says:
> If a Content-Type header field is not present, the recipient MAY either assume a media type of "application/octet-stream" or examine the data to determine its type.

When using the dashboard/browser combination the `Content-Type` header is set if the attachment type can be determined (e.g. `.png` -> `Content-Type: image/png`), but for cases where it cannot be determined it looks like the behaviour of CouchDB 1.x dashboard is to omit the header and the CouchDB 2.x dashboard sets an empty `Content-Type: `, which would result in the observed behaviour difference of an empty string vs `application/octet-stream`.

In any case java-cloudant has no code for determining an attachment type so we require the `Content-Type` header to be set, if you don't know the type of the attachment you should explicitly set it to `application/octet-stream`.

**Comment by Kenzku** [comment]
Have you tried to upload war, jar or ear files, it looks like it falls down to the "" in CouchDB 2.x content_type column?

**Comment by ricellis** [comment]
>you cannot just assume to be an png image or octet-stream at the backend

We don't.
1. java-cloudant makes no assumptions about attachment type and has no ability to make an assumption about attachment type, which is exactly why we force the `Content-Type` to be specified.
1. the server backend makes no assumptions about attachment type - it defaults to `application/octet-stream` if no `Content-Type` header is provided, which is in line with the HTTP specification.

The only thing that makes assumptions about an attachment type is a browser upload through the dashboard.

When you are uploading wars, ears or jars with java-cloudant you must set the content type appropriately e.g.
```java
db.saveAttachment(new FileInputStream("my.ear"), "my.ear", "application/octet-stream");
db.saveAttachment(new FileInputStream("my.war"), "my.war", "application/octet-stream");
db.saveAttachment(new FileInputStream("my.jar"), "my.jar", "application/octet-stream");
```
