### ISSUE TITLE
Allow to query view with multiple key

### ISSUE THREAD

**Issue by sbrunot** [cloudant/java-cloudant#42]
It seems that a view can only be queried with a single key, using the key(Object...) method of com.cloudant.client.api.View. In the meantime, cloudant allows querying using multiple keys (using query parameter keys=...), so it would be helpful to have a method that allow querying using multiple keys (for example a method keys(Object[]) on the com.cloudant.client.api.View class).

**Comment by mariobriggs** [comment]
See the [Fetch all/multiple documents](https://github.com/cloudant/java-cloudant#insertupdate-docs) section of the Readme. It has an example of example using a list

**Comment by sbrunot** [comment]
Unfortunately, this example works only when querying the "_all_docs" view... I would like to be able to query any view, using simple or complex keys. I managed to do so by adding keys(Object[]) method to the com.cloudant.client.api.View and org.lightcouch.View method, and was wondering if it could be added to the api ?

**Comment by mariobriggs** [comment]
See byComplexKey() in [viewsTest](https://github.com/cloudant/java-cloudant/blob/master/src/test/java/com/cloudant/tests/ViewsTest.java) for an example of complex keys. There is a start/end e.g. in byStartAndEndKey() too. Over and above that, we welcome Pull requests

**Comment by sbrunot** [comment]
As you can seen the byComplexKey only query with one single complex key. I'd be happy to submit a pull request: do you have a documented procedure on how to create a test account on cloudant to run the project unit tests ? I've tried to run the unit tests using a cloudant database created on Bluemix but didn't succeed...

**Comment by mariobriggs** [comment]
See #29 for another examples of complex keys with start and end. Maybe if show the http request code, i can comment better. What error did u hit with a bluemix created cloudant for running the tests, there is no difference between one created directly from cloudant.com vs bluemix

**Comment by sbrunot** [comment]
I've been able to run the tests on my database, so I've created a pull request for you to review: https://github.com/cloudant/java-cloudant/pull/43

**Comment by mariobriggs** [comment]
fixed via commit 4773586

**Comment by sivakashi** [comment]
Hi,

Please update maven dependency jar(1.0.1) with new code changes.
I am not getting keys(Object... keys) changes with dependency jar.

Thanks,

**Comment by AparnaPillai46** [comment]
I want to parse my key into objects. My key is something like this ... Is this possible ?

"key":{  
      "pId":"xxxx",
      "pType":"yyy",
      "pName":"xxx",
      "spT":"qqqq",
      "ind":"Y",
      "order":1,
      "templ":"aaaaa",
      "p":[ "aaaaa"]
   }
