### ISSUE TITLE
include_fields option with search index

### ISSUE THREAD

**Issue by HarikaSSS** [cloudant/java-cloudant#421]
Hi,

On cloudant, i can query any search index with option include_fields=["field1", "field2"]
This will include only field1, field2 in the output fields, where field1 and field2 are indexed with store=true option
I couldnot find any method in the java-cloudant search api wherein i can have this functionality. Do we really have any such method? or do we have any alternatives for this?

**Comment by ricellis** [comment]
@HarikaSSS 
The `Search` class is out of date compared to the options available on the server.
It is always possible to workaround missing API by using the [`executeRequest` method](https://static.javadoc.io/com.cloudant/cloudant-client/2.12.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) to formulate the request you want.

**Comment by ricellis** [comment]
This won't be fixed here. However, our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) has updated API models including `include_fields` for [`postSearch`](https://cloud.ibm.com/apidocs/cloudant?code=java#postsearch).
