### ISSUE TITLE
Bulk ignores cloudant responses

### ISSUE THREAD

**Issue by al-tr** [cloudant/java-cloudant#428]
- CloudantClient (java-cloudant) version(s) that are affected by this issue - 2.12.0 (and earlier)
- Java version (including vendor and platform) - java 8 - IBM J9 VM
- If you're using the optional okhttp dependency - yes
- A small code sample that demonstrates the issue - below

Validation design document:
```js
function (newDoc, oldDoc, userCtx, secObj) {
    //...
    if (!(typeof newDoc[field] === "boolean") && (!(typeof newDoc[field] === "number"))) {
        if (!newDoc[field]) {
            throw({forbidden: 'field cannot be empty' });
        }
    }
    //...
}
```

JavaModel contains `field`.
documents - a list of JavaModels
code:
```java
        try {
            JavaModel object = documents.get(0);
            object.setField(null);
            Response response = database.post(object);
            // validation function returns 403, exception is thrown
            log.info("{} {} {} {} {}", response.getId(), response.getRev(), response.getStatusCode(), response.getError(), response.getReason());
        } catch (CouchDbException ex) {
            log.info("{} {}: {}", ex.getStatusCode(), ex.getError(), ex.getReason());
        }

        List<Response> responses = database.bulk(documents);

        List<PostResult> postResults = responses.stream()
                .peek(e -> log.info("{} - {} - {} - {} - {}", e.getId(), e.getRev(), e.getStatusCode(), e.getError(), e.getReason()))
                .map(e -> new PostResult(e.getStatusCode(), e.getId(), e.getReason()))
                .collect(Collectors.toList());
```

logs:
```text
CloudantRepository - 403 forbidden: field cannot be empty
CloudantRepository - id1 - null - 201 - forbidden - Created
```
PostResult object:
```json
{
    "httpCode": 201,
    "id": "id1",
    "moreInformation": "Created"
}
```

response.getStatusCode() - always `201`
response.getReason() - always `Created`
response.getError() - `null` when there's no actual error, reason when there's

---
nasty workaround:
```java
if (e.getError() == null) {
    return new PostResult(e.getStatusCode(), e.getId(), "Successfully posted");
} else {
     return new PostResult(400, e.getId(), e.getError());
}
```

**Comment by emlaver** [comment]
@al-tr could you give me more details on what you are expecting? I don't understand this part that you wrote above: "response.getError() - null when there's no actual error, reason when there's".

Just to note, `_bulk_docs` will return either a 201 or 202 response.  More details [here in the documentation](https://console.bluemix.net/docs/services/Cloudant/api/document.html#bulk-operations).

**Comment by al-tr** [comment]
I expect to get error message body. In the documentation it's called reason, java API returns Created in any case
```
Example JavaScript to produce forbidden error as part of a validation function:


throw({forbidden: 'invalid recipe ingredient'});
Example error message from a validation function:


{
    "id" : "7f7638c86173eb440b8890839ff35433",
    "error" : "forbidden",
    "reason" : "invalid recipe ingredient"
}
```

**Comment by tomblench** [comment]
@al-tr I have opened a PR for this, #436 

Please see my comment regarding status codes. Even if document validation fails the overall status code will be 201 (202 on Cloudant if write quorum cannot be met).

**Comment by al-tr** [comment]
@tomblench thanks for the info
