### ISSUE TITLE
Functionality _bulk_get

### ISSUE THREAD

**Issue by al-tr** [cloudant/java-cloudant#429]
- CloudantClient (java-cloudant) version(s) that are affected by this issue - 2.12.0 (and earlier)
- Java version (including vendor and platform) - java 8 - IBM J9 VM
- If you're using the optional okhttp dependency - yes
- A small code sample that demonstrates the issue - below

There's a [`_bulk_get` functionality in cloudant](https://console.bluemix.net/docs/services/Cloudant/api/document.html#the-_bulk_get-endpoint).

Is it planned to implement it in the API? Or maybe it's already there in some unexpected way?

**Comment by emlaver** [comment]
@al-tr The current workaround is to use [client.executeRequest](https://static.javadoc.io/com.cloudant/cloudant-client/2.11.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) method to perform calls that are not currently available in the Java API.
For example: `HttpConnection resp = client.executeRequest(Http.GET(new URL(database.getDBUri() + "/_bulk_get")));`
We have plans to add this in the next API versions.

**Comment by al-tr** [comment]
just a funny side not:
`_bulk_get` is actually a POST request :D

**Comment by emlaver** [comment]
I've updated the example above to use POST.

**Comment by ricellis** [comment]
We're not adding enhancements here, but our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) includes APIs for [`postBulkGet`](https://cloud.ibm.com/apidocs/cloudant?code=java#postbulkget).
