### ISSUE TITLE
Functionality list view call

### ISSUE THREAD

**Issue by al-tr** [cloudant/java-cloudant#430]
- CloudantClient (java-cloudant) version(s) that are affected by this issue - 2.12.0 (and earlier)
- Java version (including vendor and platform) - java 8 - IBM J9 VM
- If you're using the optional okhttp dependency - yes
- A small code sample that demonstrates the issue - below

Didn't found anything that looks like this in the library:
```java
database.getDBUri() + "/_design/" + designDocName + "/_list/" + listName + "/" + viewName
```
Is this functionality supported? Planned?

**Comment by emlaver** [comment]
@al-tr You can use [executeRequest](https://static.javadoc.io/com.cloudant/cloudant-client/2.11.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) to make a request against `_list` and we currently have no plans to add it.  The list function performance is poor on the server side and it's better to write and call the function in Java from the client side.
