### ISSUE TITLE
Functionality update function http response

### ISSUE THREAD

**Issue by al-tr** [cloudant/java-cloudant#431]
- CloudantClient (java-cloudant) version(s) that are affected by this issue - 2.12.0 (and earlier)
- Java version (including vendor and platform) - java 8 - IBM J9 VM
- If you're using the optional okhttp dependency - yes
- A small code sample that demonstrates the issue - below

Current way of calling of an update function is only returns String, but there's also an important thing such as an http return code.
```public String invokeUpdateHandler(String updateHandlerUri, String docId, Params params)```
Are there any plans to extend update function call functionality (which sounds like an API change)? maybe in 3.x?

**Comment by emlaver** [comment]
@al-tr You can use [executeRequest](https://static.javadoc.io/com.cloudant/cloudant-client/2.11.0/com/cloudant/client/api/CloudantClient.html#executeRequest-com.cloudant.http.HttpConnection-) to get the http return code from the update function.
We intend to address this in the next major version.

**Comment by ricellis** [comment]
Update functions are deprecated in [Couch 3.x](https://docs.couchdb.org/en/stable/whatsnew/3.0.html#deprecated-feature-warnings) for removal in 4.x - we won't be adding any client side APIs for them.
