### ISSUE TITLE
search returns all documents and does not limit the result.

### ISSUE THREAD

**Issue by tanwald** [cloudant/java-cloudant#446]
If I query my search index using Cloudant Dashboard resulting in the path

`..._design/fulltext/_search/fulltext?subject%3A"check" OR body%3A"check"`

I get the expected records (2 documents).

Using the CloudantClient:

```java
String query = "subject:\"" +  filter.getSubject().trim() + "\" OR body:\"" + filter.getBody().trim() + "\"";
LOGGER.fine(query);
result = this.database.search("fulltext/fulltext")
    .limit(limit)
    .includeDocs(true)
    .query(query, this.documentType);
```

the logger within the snippet above logs

`subject:"check" OR body:"check"`

but returns all documents. Neither query nor limit seem to have any effect.

- CloudantClient
2.12.0
- Java version
Oracle 1.8
- Optional okhttp dependency.
no

**Comment by emlaver** [comment]
@tanwald I'm unable to reproduce your issue.  I tested with a search example similar to your code using our `examples.cloudant.com` account on java-cloudant 2.12 and verified the same expected result in the Cloudant dashboard.   Also, `limit` is working as expected and prints only 3 of the 5 total.
Example code and response:

```
        CloudantClient account = ClientBuilder.account("examples").build();
        Database db = account.database("animaldb", false);
        
        String id = "lemur";
        String diet = "herbivore";
        String query = "_id:\"" +  id + "\" OR diet:\"" + diet + "\"";
        
        Search srch = db.search("views101/animals");
        List<JsonObject> animals = srch.limit(3)
                .includeDocs(true)
                .query(query, JsonObject.class);
        Assertions.assertNotNull(animals);
        for (JsonObject a : animals) {
            Assertions.assertNotNull(a);
            System.out.println(a);
        }
```

>{"_id":"lemur","_rev":"3-552d9dbf91fa914a07756e69b9ceaafa","wiki_page":"http://en.wikipedia.org/wiki/Ring-tailed_lemur","min_weight":2.2,"max_weight":2.2,"min_length":0.95,"max_length":1.1,"class":"mammal","diet":"omnivore"}
{"_id":"giraffe","_rev":"3-7665c3e66315ff40616cceef62886bd8","min_weight":830,"min_length":5,"max_weight":1600,"max_length":6,"wiki_page":"http://en.wikipedia.org/wiki/Giraffe","class":"mammal","diet":"herbivore"}
{"_id":"elephant","_rev":"3-f812228f45b5f4e496250556195372b2","wiki_page":"http://en.wikipedia.org/wiki/African_elephant","min_weight":4700,"max_weight":6050,"min_length":3.2,"max_length":4,"class":"mammal","diet":"herbivore"}

**Comment by tanwald** [comment]
Thank you very much for your quick reply. It was actually a caching issue on my side. Sorry for that...
