### ISSUE TITLE
Bulk delete response cannot distinguish failure caused by the document doesn't exist or the document exist but revision doesn't match

### ISSUE THREAD

**Issue by andrewnet** [cloudant/java-cloudant#451]
The response of the bulk delete cannot distinguish failure caused by the document doesn't exist or the document exist but the revision doesn't match. For both case, the response is identical (`error` is `conflict` and `reason` is ` Document update conflict.`)

- CloudantClient (java-cloudant) version(s) that are affected by this issue.
   - cloudant-client-2.13.0.jar
- Java version (including vendor and platform).
   - JDK 1.8.0, unrelated
- If you're using the optional okhttp dependency.
   - no, unrelated
- A small code sample that demonstrates the issue.

```
		String[][] docsToDelete = new String[][] {
				// existing doc, matching rev
				{ "0a39ccf1138a1cb8a18bf6ab98bd9a18", "19-35329d54c9d490ec6f0b6e7a31970a9d" },
				// existing doc, non-matching rev
				{ "0a39ccf1138a1cb8a18bf6ab98bd3c2f", "19-ec63823276e423fde2d43f6446d95385" },
				// non-existing doc, made up id and rev
				{ "dummy_id_does_not_exist", "15-87fc0d848cc424dd162d4c03507c167a" },
				// non-existing doc, null id and made up rev
				{ null, "15-87fc0d848cc424dd162d4c03507c167a" } };

		// get cloudant client;
		CloudantClient client = null;
		Database db = client.database("mydb", false);

		List<JsonObject> docs = new ArrayList<>();
		for (int i = 0; i < docsToDelete.length; i++) {
			JsonObject doc = new JsonObject();
			doc.addProperty("_id", docsToDelete[i][0]);
			doc.addProperty("_rev", docsToDelete[i][1]);
			doc.addProperty("_deleted", true);
			docs.add(doc);
		}

		List<Response> resps = db.bulk(docs);
		for (Response response : resps) {
			System.out.println(response);
			System.out.println("  error:" + response.getError() + ", reason:" + response.getReason() + ", statusCode:"
					+ response.getStatusCode());
		}

```

Running above code, I got the response below:
```
Response [id=0a39ccf1138a1cb8a18bf6ab98bd9a18, rev=20-6760fd5e15b4c57e1881b0d2e5bfa328]
  error:null, reason:null, statusCode:201
Response [id=0a39ccf1138a1cb8a18bf6ab98bd3c2f, rev=null]
  error:conflict, reason:Document update conflict., statusCode:201
Response [id=dummy_id_does_not_exist, rev=null]
  error:conflict, reason:Document update conflict., statusCode:201
Response [id=d5f9e5a2aeb16e2ba3a7518482e911a6, rev=null]
  error:conflict, reason:Document update conflict., statusCode:201
```

Please note that the responses of the second and third case are exactly same.  As the result, you won't be able to tell if the failure caused by the document doesn't exist or the document exist but the revision doesn't match.

For the case `document doesn't exist`, it could be a result of other people deleting the same document. Since the document doesn't exist any more, there is no need to do anything. However, for the case `document exist but the revision doesn't match`, it could be a result of other people updating the same document; in which case, it needs to be retried by getting the latest revision and delete.

**Comment by smithsz** [comment]
Those errors you are seeing come straight from the server. There's no additional logic in the library to distinguish between them.

I can demonstrate this locally using cURL:
```sh
$ curl localhost:5984/example_db/doc1 -XPUT -d {}  # create new document
{"ok":true,"id":"doc1","rev":"1-967a00dff5e02add41819138abb3284d"}

$ curl localhost:5984/example_db/_bulk_docs -XPOST -Hcontent-type:application/json -d '{"docs":[{"_id":"doc1","_rev":"1-967a00dff5e02add41819138abb3284d","_deleted":true}]}'  # delete document by setting `"_deleted": true`
[{"ok":true,"id":"doc1","rev":"2-eec205a9d413992850a6e32678485900"}]

$ curl localhost:5984/example_db/_bulk_docs -XPOST -Hcontent-type:application/json -d '{"docs":[{"_id":"doc1","_rev":"1-967a00dff5e02add41819138abb3284d","_deleted":true}]}'  # attempt to delete the document again
[{"id":"doc1","error":"conflict","reason":"Document update conflict."}]
```

The only way to return the `"reason":"deleted"` response is by using the `DELETE` HTTP verb:
```sh
$ curl localhost:5984/example_db/doc1\?rev="1-967a00dff5e02add41819138abb3284d" -XDELETE
{"error":"not_found","reason":"deleted"}
```

This means in java-cloudant you'll need to call [remove](http://static.javadoc.io/com.cloudant/cloudant-client/2.13.0/com/cloudant/client/api/Database.html#remove-java.lang.String-java.lang.String-) on each document in turn rather than using the `/_bulk_docs` endpoint.

**Comment by andrewnet** [comment]
Thanks, @smithsz . 

Is there any way to enhance the cloudant server to return different response? If this is out of your scope, do you know where I can raise the issue?

**Comment by smithsz** [comment]
No, I'm afraid it's not possible to change this behaviour. It's clear that adding `"_deleted":true` takes a completely different code path internally versus using the DELETE method.

You can raise your issue [here](https://github.com/apache/couchdb/issues/new).

**Comment by andrewnet** [comment]
Thanks, @smithsz.

I am closing this issue and pursue with the new issue at https://github.com/apache/couchdb/issues/1408.
