### ISSUE TITLE
I am unable to get all revs list

### ISSUE THREAD

**Issue by umashanker088** [cloudant/java-cloudant#453]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

I am unable to get all revs list from cloudant using the java lib
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

There is no mechanism to get all revisions list of the particular document  in cloudant java lib  

But when  we are call direct call clouant api  using browser  then get the list of  revisions

.....................................db/doc?revs=true

 Environment details
Cloudant 1.8.9 
- Java version i 1.8.0_151 
- Using the optional okhttp dependency :No

**Comment by tomblench** [comment]
Use
```java
Foo foo = db.find(Foo.class, "exampleId", new Params().revisions());
```
Note that `Foo` needs to be a POJO capable of mapping the JSON returned, including the `_revisions` map.

**Comment by umashanker088** [comment]
Excellent job  thanks a lot  I will check in code level.
