### ISSUE TITLE
performace tunning parameters in cloudant DB and java api level

### ISSUE THREAD

**Issue by umashanker088** [cloudant/java-cloudant#454]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. How to increase the application performance so that can you share some important tuning parameters or approach 

Currently we are using spring boot application in which integrate Cloudant db using Cloudant java  libraries   

There are two approach to use  for get data in list from db such as 
1. View 
2. db.find call 
3. db.find query 
3. db.contains ( method taking more time so ware plan to move all check call via view  call)

I am fully confused so that kindly suggest me which is best approach use for get list of data or single document from db  

  Cloudant lib : 1.9.0
- Java version  1.8.0_151 OpenJDK macOS
- Using the optional okhttp dependency. No

**Comment by tomblench** [comment]
I can't make any specific recommendations without more detailed information.

If you know the document ID and you want to fetch one document, then use one of the `find` [methods](https://static.javadoc.io/com.cloudant/cloudant-client/2.13.0/com/cloudant/client/api/Database.html#find-java.lang.Class-java.lang.String-).

If you know the document IDs and you want to fetch a large number of documents, then use an [`AllDocsRequestBuilder`](https://static.javadoc.io/com.cloudant/cloudant-client/2.13.0/com/cloudant/client/api/views/AllDocsRequestBuilder.html), in conjunction with the `keys` method. (The last example in the list shows the use of `keys`).

Which version of java-cloudant are you using? You say you are using 1.9.0 but there is no such version. Do you mean 2.9.0?

**Comment by umashanker088** [comment]
Thanks 
 Ok fine but how to check document present in db if we can use contains  method its will take more time.
How to update some attributes without fetch to respective document with id and if we can use updatehandler some time we getting 500 internal server type of error so what i can do?    
Sorry we are using  2.9.0 cloudant java lib.

**Comment by tomblench** [comment]
- `contains` makes an HTTP HEAD call (http://docs.couchdb.org/en/2.2.0/api/document/common.html#db-doc) and should be the fastest way to find out whether a document exists. If you have benchmark data showing otherwise, we'd be interested to see.

- If you are getting a 500 internal server error there may be logic error in your updatehandler. This isn't a client libraries issue but you can contact Cloudant support (either via the dashboard or at support@cloudant.com) to troubleshoot this.

**Comment by emlaver** [comment]
Closing as stale, please reopen if you require further assistance.
