### ISSUE TITLE
The 'keys' array of a ViewMultipleRequest is not sent to the server even when it is set

### ISSUE THREAD

**Issue by sevokn** [cloudant/java-cloudant#458]
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

    package bugtest;
    
    import java.net.URL;
    import java.util.List;
    
    import com.cloudant.client.api.ClientBuilder;
    import com.cloudant.client.api.CloudantClient;
    import com.cloudant.client.api.Database;
    import com.cloudant.client.api.views.Key;
    import com.cloudant.client.api.views.MultipleRequestBuilder;
    import com.cloudant.client.api.views.ViewMultipleRequest;
    import com.cloudant.client.api.views.ViewRequestBuilder;
    import com.cloudant.client.api.views.ViewResponse;
    import com.google.gson.JsonNull;
    
    public final class CloudantKeyArrayMissingBugTest {
        
        public static void main(final String[] args) throws Exception {
            final String urlString = "<FILL_IN>";
            final URL url = new URL(urlString);
            final String username = "<FILL_IN>";
            final String password = "<FILL_IN>";
            final CloudantClient cloudantClient = ClientBuilder.url(url).username(username).password(password).build();
            final String databaseName = "<FILL_IN>";
            final boolean createDatabaseIfNotExist = true;
            final Database database = cloudantClient.database(databaseName, createDatabaseIfNotExist);
            final String designDocumentName = "<FILL_IN>";
            final String viewName = "<FILL_IN>";
            final ViewRequestBuilder viewRequestBuilder = database.getViewRequestBuilder(designDocumentName, viewName);
            final Key.Type<String> keyType = Key.Type.STRING;
            final Class<JsonNull> valueType = JsonNull.class;
            final String[] keys = new String[2];
            keys[0] = "one";
            keys[1] = "two";
            final MultipleRequestBuilder<String, JsonNull> multipleRequestBuilder = viewRequestBuilder.newMultipleRequest(keyType, valueType).keys(keys).add();
            final ViewMultipleRequest<String, JsonNull> viewMultipleRequest = multipleRequestBuilder.build();
            final List<ViewResponse<String, JsonNull>> viewResponsesList = viewMultipleRequest.getViewResponses();
        }
        
    }

### 2. What you expected to happen

The `keys` array should be included in the POST data of the view request

### 3. What actually happened

The `keys` array is not included in the POST data of the view request.

As there are no keys that limit the output, the Cloudant server returns the whole content of the view index as the result response, as all indexed entries match the query.

## Environment details
- Version(s) that are affected by this issue.
    > 2.13.0 (works with 2.12.0)
- Java version including vendor and platform
    > Oracle Java 1.8.0_181-b13 on Linux
- Using the optional okhttp dependency
    > No

**Comment by tomblench** [comment]
@sevokn thanks for reporting this. It looks like a regression introduced for the feature `[IMPROVED] When making view requests (including _all_docs), set keys in the POST body rather than in GET query parameters. This is because a large number of keys could previously exceed the maximum URL length, causing errors.`
