### ISSUE TITLE
Unable to recover from failed authentication attempt

### ISSUE THREAD

**Issue by motyd** [cloudant/java-cloudant#474]
We are seeing an issue that is not easily reproducible, but is critical as it causes us failures.

We are using the cloudant client in our cloud application, and we see that after there are some Cloudant issues (such as networking issues, or cloudant server is down for a while) the cloudant client is unable to recover and every call throws an Exception: `
```
com.cloudant.client.org.lightcouch.CouchDbException: 401 Unauthorized at 
https://<OUR CLOUDANT ACCOUNT>.cloudantnosqldb.appdomain.cloud:443/<DB_NAME>/<DOC>. at 
com.cloudant.client.org.lightcouch.CouchDbClient.execute(CouchDbClient.java:578) at 
com.cloudant.client.org.lightcouch.CouchDbClient.executeToInputStream(CouchDbClient.java:629) at
com.cloudant.client.org.lightcouch.CouchDbClient.head(CouchDbClient.java:398) at 
com.cloudant.client.org.lightcouch.CouchDatabaseBase.contains(CouchDatabaseBase.java:177) at 
com.cloudant.client.api.Database.contains(Database.java:813)

```

We also saw this in the logs:
```

Credentials are incorrect for server https://<OUR CLOUDANT ACCOUNT>.cloudantnosqldb.appdomain.cloud:443/_session, cookie authentication will not be attempted again by this interceptor object

```

The only solution was to restart the application and it resolved the issue.

We are initializing the cloudant client like so:
```
ClientBuilder.url(cloudantURL)
                    .username(username)
                    .password(password)
                    .build();
```

I cannot be sure, but it seems like after the auth cookie is expired or otherwise becomes invalid, the client gets stuck and does not attempt to retrieve a new one? 

Are we doing something wrong? Should we change the way we initialize the client, or provide other parameters? 

And we are using version 2.13.0, with the ok-http dependency also.

**Comment by motyd** [comment]
Thanks for the quick reply. 
We are certain that this is not an incorrect credentials issue as:
1.  The credentials are the same, and did not change. Restarting the applications fixed the issue with the same credentials used as before.
2. During the time those exceptions were happening, different applications (specifically Node.JS apps using the node client) were able to communicate with the same cloudant service with the same credentials.

This was observed during a time when there were intermittent issues with the cloudant service we were using, but after those issues resolved, the Node.JS applications were able to resume proper communication, while our java applications kept receiving Unauthorized errors. 

If the reason for this is an issue with the server side implementatino of  `/_session`. Is there a way to signal to the client not to use the cookie authentication and just provide the username password directly? I saw that the documentation suggest using `BasicAuthInterceptor`, but it seems like it's not a replacement, but rather an addition to the cookie mechanism.

**Comment by ricellis** [comment]
Sure you can use just a `BasicAuthInterceptor` if you want to:
```java
ClientBuilder.url(cloudantURL)
  .interceptors(new BasicAuthInterceptor("user:pass"));
  .build();
```

**Comment by motyd** [comment]
We can try that code snippet, though going over the sources it looks like the cookie interceptor will still be activated as long as username and password are provided, even if it's provided through the URL.

Another question/observation:
According to the logged error and your description of the flow, if the call to `_session` returned a 401 the client assumes that the credentials are incorrect and will NEVER attempt to re-authenticate. So for example if this endpoint returned a 401 (let's say due to a bug or server side configuration mistake) the client is entering an unusable state which it can never exit. THerefore even if the issue is fixed the client has no way to recover? Is my assumption correct and is this the desired behavior?

**Comment by ricellis** [comment]
>cookie interceptor will still be activated as long as username and password are provided, even if it's provided through the URL

Correct, so don't provide the user info in the URL if you don't want the cookie interceptor.

>if this endpoint returned a 401 due to a temporary issue (let's say due to a bug or server side configuration mistake)

If there is a server-side configuration mistake then yes, the client will need re-initializing after the configuration error is corrected.

If there is a bug where the server returns a `401` temporarily it needs fixing on the server side not working around in client code. The [HTTP spec](https://tools.ietf.org/html/rfc7235#section-3.1) says:

> >If the request included authentication credentials, then the 401 response indicates that authorization has been refused for those credentials.  The user agent MAY repeat the request with a **new or replaced** Authorization header field

>Therefore even if the issue is fixed the client has no way to recover? Is my assumption correct and is this the desired behavior for the client?

The client will not _automatically_ recover from a `401` on `_session` request. The behaviour is in line with the HTTP spec and there is the option for application developers to handle the response code as they see fit.

You can make the client recover if you feel that is appropriate for your application. For example you are completely at liberty to catch `CouchDbException` check if it is a `401` and re-initialize your `CloudantClient` object.

I think currently the client behaviour is the same for all request failures to the `_session` endpoint, but potentially it could be improved to retry for likely transient conditions (e.g. connection problems, server `5xx` errors), but I don't think the behaviour should change for `401`. The problem with retrying of the `401` case is that the client can't know whether it is transient or not and in cases where the credentials are genuinely invalid it shouldn't be retrying and it needs to fail.

**Comment by motyd** [comment]
OK. This makes sense.

It turns out that probably the root cause of this was an issue in our managed cloudant service, which caused the authentication through `_session` to fail. After that even though they resolved the issue the client side had already "given up" authenticating because it got a 401 from `_session` once.

I changed the name of the issue to more accurately reflect what was going on. I'll close this issue as it seems like we have our solution for now.

Thank you.
