### ISSUE TITLE
Why is DbInfo.docDelCount a String instead of a long?

### ISSUE THREAD

**Issue by esrose** [cloudant/java-cloudant#481]
`DbInfo.docCount` is a `long`, which I would expect. However, `DbInfo.docDelCount` is a `String` even through the database info REST API returns both values as numeric. Is there a reason the deleted count is a String instead of a long?

**Comment by ricellis** [comment]
Not that I know of, it's legacy, as far as I can see it's always been a `String` in this code base. We can't change it without breaking API until the next major, but I guess we could add another method alongside.
