### ISSUE TITLE
How to change _id field name mapping?

### ISSUE THREAD

**Issue by Lewik** [cloudant/java-cloudant#498]
How to change _id field name mapping?

**Comment by bessbd** [comment]
Hi @Lewik ,

Can you please elaborate on your question? What exactly are you trying to achieve?

**Comment by ricellis** [comment]
You need to customize the GSON serialization, so either:

* Use GSON's `@SerializedName("_id")` annotation on the field in your POJO that you want to become the doc id.

or

* Create `JsonSerializer`,`JsonDeserializer`, or `TypeAdapter` that does the field mapping you want and register it on a `GsonBuilder` instance and use [`ClientBuilder#gsonBuilder`](https://www.javadoc.io/static/com.cloudant/cloudant-client/2.18.0/com/cloudant/client/api/ClientBuilder.html#gsonBuilder-com.google.gson.GsonBuilder-) to set it on the client.

**Comment by Lewik** [comment]
I have kotlin project with mongo. And I have a lot of entities with `id`. It's possible to mass rename, but it would be cool to save `id`. And all entities are in kotlin-common so I don`t want to add any annotations to them.

**Comment by bessbd** [comment]
> I have kotlin project with mongo. And I have a lot of entities with `id`. It's possible to mass rename, but it would be cool to save `id`. And all entities are in kotlin-common so I don`t want to add any annotations to them.

Thank you for expanding the issue, @Lewik ! Does that mean suggestion 2 of @ricellis works for your use case?

**Comment by Lewik** [comment]
@bessbd Yes, `setFieldNamingStrategy` in gsonBuilder helps me an I got what I want.

**Comment by bessbd** [comment]
That's awesome! Thank you for closing the ticket. Please reopen if you need more help with this or create a new one if you run into any other issues
