### ISSUE TITLE
Extend ComplexKey to work correctly if the key is not an array

### ISSUE THREAD

**Issue by markewallace** [cloudant/java-cloudant#500]
# Bug Description
We have a view which returns data like this
```
{"rows":[
{"key":{"roleId":"HC07000159","locationName":"LOCATIONNAME"},"value":6},
{"key":{"roleId":"HC07000207","locationName":"LOCATIONNAME"},"value":3},
{"key":{"roleId":"HC07000275","locationName":"LOCATIONNAME"},"value":9}
]}
```
Note the key is not an array 
The `Key` implementation won't handle this because of this code: https://github.com/cloudant/java-cloudant/blob/master/cloudant-client/src/main/java/com/cloudant/client/api/views/Key.java#L283-L287

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Create a view which has a Key which is a JSON object

### 2. What you expected to happen
The `View.Row` can handle this key value

### 3. What actually happened
The key value cannot be deserialized and is set to null

## Environment details
Latest versions

**Comment by mojito317** [comment]
see https://github.com/cloudant/java-cloudant/issues/386
Object member ordering is not guaranteed in most JSON implementations so we don't support object keys in views (because we can't guarantee that the order is preserved between client and server) - it is not advised to use objects as the key for a view for this reason.

**Comment by ricellis** [comment]
We'd still advise against using objects as keys in views for the reasons outlined above. However, in our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) it is not restricted.
