### ISSUE TITLE
Getting 401 response as cookies are not set in requests

### ISSUE THREAD

**Issue by Lalit-Bharate** [cloudant/java-cloudant#506]
###  Bug Description
We are trying to connect to the Cloudant database using java client.
First it gets AuthSession by executing POST request to https://cloudant-host:443/_session .
Here we get 200 OK response and AuthSession info. Then it says that it is storing a cookie. And cookies are stored for URIs: [http://cloudant-host]
Here is the response for _session-

https://<cloudant-host>:443/_session response headers {null=[HTTP/1.1 200 OK], Server=[CouchDB/2.1.1 (Erlang OTP/20)], X-Content-Type-Options=[nosniff], X-Cloudant-Backend=[bm-cc-us-south-04], X-Cloudant-Request-Class=[unlimited], Date=[Wed, 15 Apr 2020 12:54:57 GMT], Via=[1.1 lb2.bm-cc-us-south-04 (Glum/1.88.0)], X-Frame-Options=[DENY], X-Cloudant-Action=[cloudantnosqldb.session.write], Strict-Transport-Security=[max-age=31536000], Cache-Control=[must-revalidate], Set-Cookie=[AuthSession=<session_id>; Version=1; Expires=Thu, 16-Apr-2020 12:54:58 GMT; Max-Age=86400; Path=/; HttpOnly; Secure], Content-Length=[57], Content-Type=[application/json]}

Next, we start querying data from Cloudant. However, it fails with 401 Unauthorized response.
Somehow It is unable to find cookie values to set in the request header. AuthSession is missing in the request header.

Here is request header-
request headers {Accept=[application/json], User-Agent=[java-cloudant/2.17.0/1.8.0_211/IBM Corporation/Linux/ppc64le]}
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
We are using below code to connect to Cloudant-
CloudantClient client = ClientBuilder.account(cloudantUsername).username(cloudantApiKey).password(cloudantApiPw).build();
this.db = client.database(dbName, false);

InputStream inputStream = null;
try {
	inputStream = db.find(CONFIG_FILE_ID);
	return CharStreams.toString(new InputStreamReader(inputStream, "UTF-8"));
}

### 2. What you expected to happen
Cookie-based authentication should work as expected. AuthSession information should be used in subsequent requests.

### 3. What actually happened
It has not set AuthSession info in follow up requests which caused in 401 error from the Cloudant.
[cloudant.log](https://github.com/cloudant/java-cloudant/files/4491339/cloudant.log)

## Environment details
Cloudant Client - 2.17.0

Java version including vendor - 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 8.0.5.37 - pxl6480sr5fp37-20190618_01(SR5                                                                                                               FP37))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20190                                                                                                              617_419755 (JIT enabled, AOT enabled)
OpenJ9   - 354b31d
OMR      - 0437c69
IBM      - 4972efe)
JCL - 20190606_01 based on Oracle jdk8u211-b25

Using the optional okhttp dependency - Yes
com.squareup.okhttp3:okhttp-urlconnection:4.0.0

This java application is hosted on HMC. Below are HMC details-
*OS Embedded Operating Systems
*DS Platform Firmware
*RM V9R1.941.0

**Comment by bessbd** [comment]
Hi @Lalit-Bharate ,

Thank you for this ticket!
Looking at the environment details, there is
> Cloudant Client - 2.17.0

and the latest available release is https://github.com/cloudant/java-cloudant/releases/tag/2.19.0 which has improvements for session handling. Also, for `okhttp-urlconnection`, the supported version is `3.12.5`. 

Can you please let us know if the problem you are encountering still appears with `2.19.0` for `java-cloudant` and `3.12.5` for `okhttp-urlconnection`?

**Comment by Lalit-Bharate** [comment]
@bessbd Yes. I will try with latest version of Cloudant Client. First, I will try without any okhttp dependency.

**Comment by Lalit-Bharate** [comment]
It was the issue with cloudant client host timezone not properly set and date-time being out of sync as that of Cloudant DB. It caused cookies set by the server to be considered as expired on cloudant client.
