### ISSUE TITLE
the amount of TCP connection 

### ISSUE THREAD

**Issue by wshwbluebird** [cloudant/java-cloudant#507]
## Problem
```
CloudantClient client = ClientBuilder.url(new URL("http://ubuntu13107:5984"))
                    .username("admin")
                    .password("admin")
                    .maxConnections(1)
                    .build();
Database db = client.database("data", true);
db.query(...);
client.shutdown();
```
I run this code and it works normally.  But there are 2 TCP connections to my database during the process and there is still 1 TCP connection left after ```client.shutdown()``` is called(JVM is still running).
How can I remove all TCP connections after ```client.shutdown()```

**Comment by bessbd** [comment]
Hi @wshwbluebird,

Thank you for this ticket!

Can you please describe how to reproduce the issue and what exactly are you trying to achieve? Ie. why is it important that there is no more connection left open after calling `shutdown()`?

**Comment by wshwbluebird** [comment]
Thank you for your reply 
```
CloudantClient client = ClientBuilder.url(new URL("http://host:5984"))
                    .username("admin")
                    .password("admin")
                    .build();
client.shutdown();
while(true)
```
Running the code above and use `lsof -a -i4 -i6 -itcp` to check tcp connection. You will find that there is a TCP connection which cannot be closed
In our case, we build many CloudantClient on our platform and many connections left. Those left connections make our CouchDB unavailable.

I think the problem is in the `CookieInterceptorBase.java` located in package `com.cloudant.http.internal.interceptors` as below
```
// code in function requestCookie(HttpConnectionInterceptorContext context)
if (sessionId.equals(context.getState(this, sessionStateName, UUID.class))) {
                // Get a write lock and re-check the state
                sessionLock.readLock().unlock();
                sessionLock.writeLock().lock();
                try {
                    if (sessionId.equals(context.getState(this, sessionStateName, UUID.class))) {
                        HttpConnection sessionConn = makeSessionRequest(sessionRequestUrl,
                                getSessionRequestPayload(context), sessionRequestMimeType, context);
                        storeCookiesFromResponse(sessionConn.getConnection());
                        // We renewed a cookie, update the global sessionID and this request's context
                        sessionId = UUID.randomUUID();
                        context.setState(this, sessionStateName, sessionId);
                    }
                } finally {
                    // Downgrade to the read lock
                    sessionLock.readLock().lock();
                    sessionLock.writeLock().unlock();
                }
```
The Inputstream in ```sessionConn``` is not closed after getting cookies. 

I have tried adding a ```sessionConn.getConnection().getInputStream().close();```  and it works

**Comment by ricellis** [comment]
We used to do this, but it looks like it was regressed by #491 - I'll open a PR

**Comment by bessbd** [comment]
Hi @wshwbluebird ,
With #508 merged, can you please confirm that the issue you were experiencing is resolved now?
