### ISSUE TITLE
When is "findByIndex" and related functions actually being removed?

### ISSUE THREAD

**Issue by JamesBlandford** [cloudant/java-cloudant#514]
At the moment, the findByIndex function is tagged as Deprecated, but thats been the same since around 2.15.x 

when is this going to be fully removed?

**Comment by ricellis** [comment]
As per semantic versioning they would be removed in the next major release of this library. That said we don't have any plans to do another major release of this library before it is replaced by https://github.com/IBM/cloudant-java-sdk (which is currently in beta). I don't have a definitive timeline on that, but there will be a substantial notice period.

**Comment by JamesBlandford** [comment]
Thanks Rich, very useful information. We were very worried that it had a "Deprecated" tag and need to deploy within a month. 

We will be migrating in the future to the new cloudant Java client, but that might take a lot longer than the timescale we have!
