### ISSUE TITLE
When using QueryBuilder, the and Operation sometimes doesn't emit an array

### ISSUE THREAD

**Issue by esrose** [cloudant/java-cloudant#515]
## Bug Description
When I instantiate a QueryBuilder with an and Operation containing only a single Selector, the resulting JSON does not have an array for the $and field inside the selector.

I'm an IBM Cloudant customer.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

1. Create a QueryBuilder: `QueryBuilder builder = new QueryBuilder(and(eq("userId", "myUser")));`
2. Execute the query against an existing database: `database.query(builder.build(), JsonObject.class);`

Alternatively, inspect the `selector` variable on the QueryBuilder after step 1 to see the incorrect JSON. For example, `"$and": {"userId": {"$eq": "myUser"}}`

### 2. What you expected to happen
I expect QueryBuilder to emit JSON which is accepted by CouchDB, meaning $and should always be an array regardless of how many elements are in it.

### 3. What actually happened
CouchDB gives me a 400 error from the _find endpoint because the $and is malformed.

## Environment details
- Version(s) that are affected by this issue.
    > 2.18.0 and 2.19.1 are the only versions I checked, both are affected.
- Java version including vendor and platform
    > OpenJDK 11.0.4 macOS
- Using the optional okhttp dependency.
    > No

I'm executing the query against CouchDB 3 in my local dev environment.

**Comment by mojito317** [comment]
Hi @esrose! First of all, thank you for the bug report!

Now you cannot use `$and` with a single selector, we will work on the fix.

Till then, you can use `QueryBuilder builder = new QueryBuilder(eq("userId", "myUser"))` on your  single single selectors. E.g.:

```java
if (selectorArray.length == 1) {
 new QueryBuilder(selectorArray[0])
} else {
 new QueryBuilder(and(selectorArray))
}
```
