### ISSUE TITLE
Is it compatible with CouchDB 3.1.1?

### ISSUE THREAD

**Issue by lazycodersps** [cloudant/java-cloudant#519]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Hi, I am not sure if it is the right place to ask this question or it's a silly question, but just wanted to check if we can use this with CouchDB 3.1.1. Currently we are using ektorp and planning to migrate it to some other java client like yours(`java-cloudant`, if it is compatible). Thanks for your support.

**Comment by mojito317** [comment]
Hi @lazycodersps!

Yeah, this lib can be used with CouchDB 3.1.1, but please keep in mind that we don't have any plans to do another major release of this library before it is replaced by our new [cloudant-java-sdk](https://github.com/IBM/cloudant-java-sdk/)(beta) which is also compatible with CouchDB 3.1.1 for data operations.

**Comment by lazycodersps** [comment]
@mojito317 , Thank you very much for the information.
