### ISSUE TITLE
No debug information included in jar

### ISSUE THREAD

**Issue by stephenrobertson0** [cloudant/java-cloudant#52]
Hi

I'm trying to set breakpoints in the Cloudant lib code from within IntelliJ IDEA, but it's not working. This can happen if a jar is built but no debug information is included. If this is a case, could you release a new jar version that includes debug information?

Thanks!

**Comment by brhaible** [comment]
+1
I often want to know what URL a certain query through the View API is doing. To do this, I need to set a breakpoint in the method org.lightcouch.View.queryForStream - which is impossible if the jar file is compiled without debug information.
