### ISSUE TITLE
View.keys(Object... keys) method not available in maven dependency jar(1.0.1)

### ISSUE THREAD

**Issue by sivakashi** [cloudant/java-cloudant#70]
Hi,

Please update maven dependency jar(1.0.1) with new code changes.
I am not getting keys(Object... keys) changes with dependency jar.

Old Issue link:
https://github.com/cloudant/java-cloudant/issues/42

Thanks,

**Comment by rhyshort** [comment]
Currently `View.keys(Object... keys)` API doesn't work in all cases right now, it is being actively worked on in PR #63. We'll work on getting a release out once that PR has been merged.

**Comment by sivakashi** [comment]
Thanks @rhyshort, for now we will take care of it by building jar from source code.

**Comment by emlaver** [comment]
@sivakashi could you please provide an example? Is it similar to https://github.com/cloudant/java-cloudant/issues/29?

**Comment by sivakashi** [comment]
Hi @rhyshort,
Yes its similar to #29.
EX:
Complex key is a combination of String and Integer.
["1000",0] -- every complex key contains multiple child records
["1000",1]
["1000",2]
["1001",0]
["1001",1]
["1001",2]
["1002”,0]
So on...

Here my requirement is like I have to get all child records from my view's emit data(include_docs=false) based one passed complex keys, startKey and endKey option will not useful for my requirement(multiple start and end keys will not accepted by API), so I have used View.keys(Object... keys) method(From java I am preparing complex keys by using List<List<Object>>).
Sample Keys:
{"keys":
[
["1000",0],
["1000",1],
["1000",2],
["1001",0],
["1001",1],
["1001",2],
["1002",0],
["1002",1],
["1002",2]
]
}

This Java API call is working fine for my requirement.

**Comment by ricellis** [comment]
The `View.keys(Object... keys)` method should be available in 1.1.0+

**Comment by ptommasi** [comment]
I think that in version 2.5 adding an object as complex key element is private, therefore not available. 

In my case I have and index formed of a string and a number (eg: `[ "userA", 123 ]`) and I'm trying to get all the document for a given user, which translate into a scan from `["userA", null]` to `["userA", {}]`.

Simplified code looks like:

```
private static final String firstKey = null;
private static final String lastKey = "";

ViewRequestBuilder viewBuilder = db.getViewRequestBuilder("designDoc", "userTimeView");

UnpaginatedRequestBuilder<ComplexKey, JsonNull> requestBuilder = viewBuilder.newRequest(Key.Type.COMPLEX, JsonNull.class);

requestBuilder = requestBuilder.startKey(Key.complex("userA").add(firstKey));
requestBuilder = requestBuilder.endKey	(Key.complex("userB").add(lastKey));

ViewRequest<ComplexKey, JsonNull> metarequest = requestBuilder.build();
```

Since I'm dealing with numbers, using a null and an empty string does the trick, but I would have liked declaring the first and last key like:

```
private static final Object firstKey = null;
private static final Object lastKey = new Object();
```

**Comment by ricellis** [comment]
@ptommasi see #147

**Comment by stephen-kruger** [comment]
I'm struggling to get this to work through the api, and the above methods seem no longer available, so restarting this thread.
For this example I have 4 keys I'm trying to query, the last 2 should be wildcard : 
`
Key.ComplexKey startKey = Key.complex(getUserUid(),getTenantUid(),"","\ufff0");
Key.ComplexKey endKey = Key.complex(getUserUid(),getTenantUid(),"","\ufff0");

getView(db)
.newRequest(Key.Type.COMPLEX,Card.class)
					.startKey(startKey)
					.endKey(endKey)
					.inclusiveEnd(true)
					.includeDocs(true)
					.skip(skip)
					.limit(limit)
					.descending(descending)
					.build().getResponse().getValues();
`
and it's not returning any values at all. Is there an alternative way of doing this?

**Comment by ricellis** [comment]
@stephen-kruger your example shows:

```java
Key.ComplexKey startKey = Key.complex(getUserUid(),getTenantUid(),"","\ufff0");
Key.ComplexKey endKey = Key.complex(getUserUid(),getTenantUid(),"","\ufff0");
```

The last element of your `startKey` and `endKey` are both the high value sentinel. So your result will be constrained to keys with that element at the end of the array. I think to get the results you want you need the start/end keys:

```java
Key.ComplexKey startKey = Key.complex(getUserUid(),getTenantUid());
Key.ComplexKey endKey = Key.complex(getUserUid(),getTenantUid(),"\ufff0","\ufff0");
```

**Comment by stephen-kruger** [comment]
My apologies - that was a typo. In fact empty string works as well.
The issue turned out to be I was using setDescending(true/false) - after much digging through the docs it turns out using descending with any multiple keys immediately breaks the query.

I'm now having to reevaluate using Views at all, since it's impossible to order the returned results on a multi-key query, making it pretty much useless for any paging use.

**Comment by ricellis** [comment]
I'm not sure if this explains your issue, but when using `descending=true` the [`startKey` and `endKey` need to be reversed](http://guide.couchdb.org/draft/views.html#reversed).

We do have built in paging - the `ViewRequestBuilder` has a [`newPaginatedRequest` method](http://static.javadoc.io/com.cloudant/cloudant-client/2.7.0/com/cloudant/client/api/views/ViewRequestBuilder.html#newPaginatedRequest-com.cloudant.client.api.views.Key.Type-java.lang.Class-). When using this class to page backwards the `descending` flag and start and end keys are swapped automatically as necessary.
