### ISSUE TITLE
Doc: the download link to the cloudant-client jar is backlevel

### ISSUE THREAD

**Issue by djboulia** [cloudant/java-cloudant#81]
Suggest just pointing to the top level repo so that you don't have to keep updating the location of the jar file.  That is, https://repo1.maven.org/maven2/com/cloudant/cloudant-client/ vs. https://repo1.maven.org/maven2/com/cloudant/cloudant-client/1.0.1/cloudant-client-1.0.1.jar

**Comment by ricellis** [comment]
Fixed in the `README.md` for 1.2.0
