### ISSUE TITLE
How to handle error responses?

### ISSUE THREAD

**Issue by nasht00** [cloudant/java-cloudant#82]
The README gives very simple examples like
`Response response = db.remove(foo);`

However it does not say what is supposed to happen in case of issues, such as a document not found, or any other error for any method.

Can someone clarify that?
Exceptions? Null response? Response with some error property?

How to check whether the request was completed successfully or not...

**Comment by ricellis** [comment]
All the issue circumstances I have seen throw a `org.lightcouch.CouchDbException`. The exception hierarchy is:
* `RuntimeException`
    * `CouchDbException`
        * `DocumentConflictException` `NoDocumentException` `PreconditionFailedException`

So if you try to remove a document that does not exist you will get a `NoDocumentException` and if there was another issue, such as a server error, you would get a `CouchDbException`. There is [a little bit of javadoc](http://static.javadoc.io/com.cloudant/cloudant-client/1.1.2/org/lightcouch/CouchDbException.html) for these exceptions.

As you can see all the exceptions currently extend `RuntimeException` and are unchecked and not specified in the method signatures of e.g. `db.remove()`. Personally I would rather see specified checked exceptions to make it more clear what the error conditions are. Although it would be a breaking API change it is something I would like to consider for a future major version.
