### ISSUE TITLE
Cloudant query sample code not correct

### ISSUE THREAD

**Issue by adasilva70** [cloudant/java-cloudant#85]
The Cloundant query sample snippet code below is not correct:

List<Movie> movies = db.findByIndex("{
                     \"Movie_year\": {\"$gt\": 1960}, \"Person_name\": \"Alec Guinness\"
                     }",
                    Movie.class,
                    new FindByIndexOptions()
                        .sort(new IndexField("Movie_year", SortOrder.desc))
                        .fields("Movie_name").fields("Movie_year"));

I tried something similar:

String Selector="{\"Place_id\": {\"$gt\": 100}}";
   List<places> p1 = db_use.findByIndex(Selector,places.class);

and got a JSON exception:

org.lightcouch.CouchDbException: Bad Request{"error":"bad_request","reason":"invalid UTF-8 JSON"} 

After adding "selector" to the query it then worked:

String Selector="\"selector\": {\"Place_id\": {\"$gt\": 100}}";

**Comment by rhyshort** [comment]
Thanks for spotting this, where is the incorrect snippet located in the docs?

**Comment by adasilva70** [comment]
It is here https://github.com/cloudant/java-cloudant#cloudant-query
Just scroll down a bit and you will see the code about List movies.

**Comment by mikerhodes** [comment]
I corrected the doc, thanks for the report!

https://github.com/cloudant/java-cloudant#cloudant-query
