### ISSUE TITLE
Get new _rev using invokeUpdateHandler

### ISSUE THREAD

**Issue by robertovivian** [cloudant/java-cloudant#93]
Is there a way to get the new _rev field using the invokeUpdateHandler method to invoke an in-line update in Cloudant? 
Actually the class `com.cloudant.client.api.Database` expose only the method `public String invokeUpdateHandler` that returns the response stream of the update operation. But the new _rev field is in the header of the http response (https://wiki.apache.org/couchdb/Document_Update_Handlers#Response). 
So, is there a way to get it?

**Comment by ricellis** [comment]
Currently there is no way in the API, but you can workaround using the `CloudantClient#executeRequest` method. For example in version 1.x something like:
```java
HttpPut putRequest = new HttpPut(client.getBaseUri().toString() 
        + "_design/yourDesignDoc/_update/yourUpdateHandler/yourDocId");
HttpResponse r = client.executeRequest(putRequest);
String rev = r.getFirstHeader("X-Couch-Update-NewRev");
```

Note that in the master branch this API has changed and would be something like:
```java
HttpConnection putRequest = Http.PUT(client.getBaseUri().toString() 
        + "_design/yourDesignDoc/_update/yourUpdateHandler/yourDocId");
HttpConnection response = client.executeRequest(putRequest);
String rev = response.getConnection().getHeaderField("X-Couch-Update-NewRev");
```

**Comment by ricellis** [comment]
Thinking about this as an enhancement going forwards, to expose the headers would require adding a new variant of `invokeUpdateHandler` or changing the return type. One option would be to use the `Response` class, which currently has status codes, but does not expose headers or body. It would need extending or a new type added. That is quite a big change, which given this has a workaround I don't think is urgent so I'm going to mark this a possible enhancement for a 3.0.0, when there is the opportunity for API changes.

**Comment by ricellis** [comment]
Update functions are deprecated in [Couch 3.x](https://docs.couchdb.org/en/stable/whatsnew/3.0.html#deprecated-feature-warnings) for removal in 4.x - we won't be adding any client side APIs for them.
